var VOCAB={
greetings:[
{l:'Oli otya',e:'How are you?',p:'oh-lee oh-tyah',ic:'🙋'},
{l:'Bulungi',e:'Fine / Good',p:'boo-loon-gee',ic:'😊'},
{l:'Webale',e:'Thank you',p:'weh-bah-leh',ic:'🙏'},
{l:'Webale nyo',e:'Thank you very much',p:'weh-bah-leh nyoh',ic:'🙏'},
{l:'Ssebo',e:'Sir / Mr',p:'seh-bo',ic:'👨'},
{l:'Nnyabo',e:'Madam / Mrs',p:'nyah-bo',ic:'👩'},
{l:'Nedda',e:'No',p:'neh-dah',ic:'🚫'},
{l:'Yee',e:'Yes',p:'yeh',ic:'✅'},
{l:'Nkusaba',e:'Please',p:'n-koo-sah-bah',ic:'🤲'},
{l:'Nsonyiwa',e:'Sorry / Excuse me',p:'n-son-yee-wah',ic:'😔'},
{l:'Bambi',e:'Please / Poor thing',p:'bam-bee',ic:'💛'},
{l:'Wasuze otya',e:'Good morning',p:'wah-soo-zeh oh-tyah',ic:'🌅'},
{l:'Osibye otya',e:'Good afternoon',p:'oh-see-beh oh-tyah',ic:'☀️'},
{l:'Sula bulungi',e:'Good night',p:'soo-lah boo-loon-gee',ic:'🌙'},
{l:'Tulabye',e:'Goodbye',p:'too-lah-byeh',ic:'👋'},
{l:'Kale',e:'Okay / Alright',p:'kah-leh',ic:'👍'},
{l:'Nkwagala',e:'I love you',p:'n-kwah-gah-lah',ic:'❤️'},
{l:'Simanyi',e:'I don\'t know',p:'see-mahn-yee',ic:'🤷'},
{l:'Nkimanyi',e:'I know it',p:'n-kee-mahn-yee',ic:'💡'},
{l:'Mazima',e:'Truth / Truly',p:'mah-zee-mah',ic:'💯'},
{l:'Amaama',e:'Delicious / Great',p:'ah-mah-mah',ic:'😋'},
{l:'Kati',e:'Now / So',p:'kah-tee',ic:'⏱️'},
{l:'Gyebale',e:'Well done',p:'jeh-bah-leh',ic:'👏'},
{l:'Mpulira',e:'I understand',p:'m-poo-lee-rah',ic:'💡'},
{l:'Erinnya lyange nze',e:'My name is...',p:'eh-reen-yah lyahn-geh n-zeh',ic:'🪪'},
{l:'Ova wa',e:'Where are you from?',p:'oh-vah wah',ic:'🌍'},
{l:'Nva',e:'I am from',p:'n-vah',ic:'📍'},
{l:'Osula wa',e:'Where do you live?',p:'oh-soo-lah wah',ic:'🏠'},
{l:'Nze',e:'Me / I',p:'n-zeh',ic:'🫵'},
{l:'Saawa mmeka',e:'What time is it?',p:'sah-wah meh-kah',ic:'⏰'},
{l:'Kyoka',e:'But / However',p:'choh-kah',ic:'↩️'},
{l:'Mwattu',e:'My goodness',p:'mwah-too',ic:'🫢'},
{l:'Tukutendereza',e:'We praise you',p:'too-koo-ten-deh-reh-zah',ic:'🙌'},
{l:'Nkusaba nnyo',e:'I beg you please',p:'n-koo-sah-bah nyoh',ic:'🙏'},
{l:'Erinnya lyo ggwe ani',e:'What is your name?',p:'eh-reen-yah lyoh gweh ah-nee',ic:'🪪'},
{l:'Katonda',e:'God / Creator',p:'kah-tohn-dah',ic:'🌟'},
{l:'Nkwagala nyo',e:'I love you very much',p:'n-kwah-gah-lah nyoh',ic:'❤️'},
{l:'Lwaki',e:'Why?',p:'lwah-kee',ic:'🤔'},
{l:'Kirungi',e:'It is good / Fine',p:'kee-roon-gee',ic:'✅'},
{l:'Tugende',e:'Let us go',p:'too-gehn-deh',ic:'🚶'},
{l:'Tujje',e:'Let us come',p:'too-jeh',ic:'🏃'},
{l:'Bannange',e:'My people / Friends',p:'bahn-nahn-geh',ic:'👥'},
{l:'Ayi',e:'Wow / Exclamation',p:'ah-yee',ic:'😮'},
{l:'Mboozi',e:'Conversation / Chat',p:'m-boh-zee',ic:'💬'},
{l:'Luganda',e:'The Luganda language',p:'loo-gahn-dah',ic:'🗺️'},
{l:'Oluzungu',e:'English language',p:'oh-loo-zoo-ngoo',ic:'🇬🇧'},
{l:'Bwetaba',e:'When you participate',p:'bweh-tah-bah',ic:'🙋'},
{l:'Okulabirira',e:'To take care',p:'oh-koo-lah-bee-ree-rah',ic:'💚'},
{l:'Ndi bulungi',e:'I am fine',p:'n-dee boo-loon-gee',ic:'😊'},
{l:'Oyagala ki',e:'What do you want?',p:'oh-yah-gah-lah kee',ic:'🤔'}
],
people:[
{l:'Maama',e:'Mother',p:'mah-mah',ic:'👩'},
{l:'Taata',e:'Father',p:'tah-tah',ic:'👨'},
{l:'Omwana',e:'Child',p:'ohm-wah-nah',ic:'👶'},
{l:'Abaana',e:'Children',p:'ah-bah-nah',ic:'👧'},
{l:'Mukyala',e:'Wife',p:'moo-chah-lah',ic:'👰'},
{l:'Omusajja',e:'Man / Husband',p:'oh-moo-sah-jah',ic:'🧔'},
{l:'Muganda',e:'Sibling / Relative',p:'moo-gahn-dah',ic:'🤝'},
{l:'Jjajja',e:'Grandparent',p:'jah-jah',ic:'👴'},
{l:'Kojja',e:'Uncle (maternal)',p:'koh-jah',ic:'👦'},
{l:'Ssenga',e:'Aunt (paternal)',p:'seh-ngah',ic:'👧'},
{l:'Omuntu',e:'Person',p:'oh-moon-too',ic:'🧑'},
{l:'Abantu',e:'People',p:'ah-bahn-too',ic:'👥'},
{l:'Munnange',e:'My friend',p:'moon-nahn-geh',ic:'🤗'},
{l:'Kabaka',e:'King',p:'kah-bah-kah',ic:'👑'},
{l:'Nnaalinnya',e:'Queen',p:'nah-leen-yah',ic:'👸'},
{l:'Musomesa',e:'Teacher',p:'moo-soh-meh-sah',ic:'👩‍🏫'},
{l:'Omusawo',e:'Doctor',p:'oh-moo-sah-woh',ic:'👨‍⚕️'},
{l:'Omukazi',e:'Woman',p:'oh-moo-kah-zee',ic:'👩'},
{l:'Omuwala',e:'Girl',p:'oh-moo-wah-lah',ic:'👧'},
{l:'Omulenzi',e:'Boy',p:'oh-moo-lehn-zee',ic:'👦'},
{l:'Omulimi',e:'Farmer',p:'oh-moo-lee-mee',ic:'👨‍🌾'},
{l:'Mugole',e:'Bride / Groom',p:'moo-goh-leh',ic:'💒'},
{l:'Omukulu',e:'Elder',p:'oh-moo-koo-loo',ic:'🧓'},
{l:'Mwana wa mwana',e:'Grandchild',p:'mwah-nah wah mwah-nah',ic:'🧒'},
{l:'Omukwano',e:'Friend',p:'oh-moo-kwah-noh',ic:'🤝'},
{l:'Omupagisi',e:'Nurse',p:'oh-moo-pah-gee-see',ic:'👩‍⚕️'},
{l:'Mufuzi',e:'Driver',p:'moo-foo-zee',ic:'🚗'},
{l:'Mulimu',e:'Worker',p:'moo-lee-moo',ic:'👷'},
{l:'Omukugu',e:'Expert / Skilled person',p:'oh-moo-koo-goo',ic:'🎓'},
{l:'Omuddu',e:'Servant',p:'oh-moo-doo',ic:'🙇'},
{l:'Ssaabasajja',e:'Head of household',p:'sah-bah-sah-jah',ic:'👨‍👩‍👧‍👦'},
{l:'Omwogezi',e:'Spokesperson',p:'ohm-woh-geh-zee',ic:'🎤'},
{l:'Omukopi',e:'Peasant / Commoner',p:'oh-moo-koh-pee',ic:'🌾'},
{l:'Omwana omuto',e:'Baby / Young child',p:'ohm-wah-nah oh-moo-toh',ic:'👶'},
{l:'Muzungu',e:'Foreigner / White person',p:'moo-zoo-ngoo',ic:'🌍'},
{l:'Omubbi',e:'Thief',p:'oh-moo-bee',ic:'🫷'},
{l:'Omukiiko',e:'Council member',p:'oh-moo-kee-koh',ic:'🏛️'},
{l:'Omubuuzi',e:'Questioner / Lawyer',p:'oh-moo-boo-zee',ic:'⚖️'},
{l:'Omuliraanwa',e:'Neighbor',p:'oh-moo-lee-rahn-wah',ic:'🏘️'},
{l:'Omugabirizi',e:'Donor / Provider',p:'oh-moo-gah-bee-ree-zee',ic:'🎁'},
{l:'Omuweereza',e:'Waiter / Attendant',p:'oh-moo-weh-reh-zah',ic:'🍽️'},
{l:'Omugenzi',e:'Traveller / Visitor',p:'oh-moo-gehn-zee',ic:'🧳'},
{l:'Omukuumi',e:'Guard / Protector',p:'oh-moo-koo-mee',ic:'🛡️'},
{l:'Omuzannyi',e:'Player / Athlete',p:'oh-moo-zahn-yee',ic:'⚽'},
{l:'Omwimbi',e:'Singer',p:'ohm-weem-bee',ic:'🎤'},
{l:'Omukozi',e:'Labourer / Worker',p:'oh-moo-koh-zee',ic:'⚒️'},
{l:'Omufuzi',e:'Pilot / Operator',p:'oh-moo-foo-zee',ic:'✈️'},
{l:'Omulenzi omuto',e:'Little boy',p:'oh-moo-lehn-zee oh-moo-toh',ic:'👦'},
{l:'Omuwala omuto',e:'Little girl',p:'oh-moo-wah-lah oh-moo-toh',ic:'👧'},
{l:'Omwami',e:'Husband / Lord',p:'ohm-wah-mee',ic:'🧑'},
{l:'Omupolisi',e:'Police officer',p:'oh-moo-poh-lee-see',ic:'👮'}
],
body:[
{l:'Omutwe',e:'Head',p:'oh-moo-tweh',ic:'🗣️'},
{l:'Amaaso',e:'Eyes',p:'ah-mah-soh',ic:'👁️'},
{l:'Okutu',e:'Ear',p:'oh-koo-too',ic:'👂'},
{l:'Ennyindo',e:'Nose',p:'eh-nyeen-doh',ic:'👃'},
{l:'Akamwa',e:'Mouth',p:'ah-kahm-wah',ic:'👄'},
{l:'Amenyo',e:'Teeth',p:'ah-meh-nyoh',ic:'🦷'},
{l:'Omukono',e:'Hand / Arm',p:'oh-moo-koh-noh',ic:'🖐️'},
{l:'Okugulu',e:'Leg / Foot',p:'oh-koo-goo-loo',ic:'🦵'},
{l:'Ekitutu',e:'Stomach',p:'eh-kee-too-too',ic:'🫃'},
{l:'Omutima',e:'Heart',p:'oh-moo-tee-mah',ic:'❤️'},
{l:'Enviiri',e:'Hair',p:'en-vee-ree',ic:'💇'},
{l:'Obulamu',e:'Life / Health',p:'oh-boo-lah-moo',ic:'🌱'},
{l:'Obulwadde',e:'Illness / Sickness',p:'oh-boo-lwah-deh',ic:'🤒'},
{l:'Amagulu',e:'Legs',p:'ah-mah-goo-loo',ic:'🦶'},
{l:'Omugongo',e:'Back',p:'oh-moo-gohn-goh',ic:'🫁'},
{l:'Akabega',e:'Shoulder',p:'ah-kah-beh-gah',ic:'💪'},
{l:'Ensaayi',e:'Blood',p:'en-sah-yee',ic:'🩸'},
{l:'Olunyi',e:'Pain',p:'oh-loo-nyee',ic:'😣'},
{l:'Akaleero',e:'Tongue',p:'ah-kah-leh-roh',ic:'👅'},
{l:'Engalo',e:'Fingers',p:'en-gah-loh',ic:'🖐️'},
{l:'Ekyena',e:'Knee',p:'eh-cheh-nah',ic:'🦵'},
{l:'Amatwi',e:'Ears',p:'ah-mah-twee',ic:'👂'},
{l:'Obutonde',e:'Strength',p:'oh-boo-tohn-deh',ic:'💪'},
{l:'Omumiro',e:'Throat',p:'oh-moo-mee-roh',ic:'🗣️'},
{l:'Omusana',e:'Skin',p:'oh-moo-sah-nah',ic:'🧴'},
{l:'Olutindo',e:'Neck',p:'oh-loo-teen-doh',ic:'🦒'},
{l:'Omugulu',e:'Foot',p:'oh-moo-goo-loo',ic:'🦶'},
{l:'Olubuto',e:'Womb / Belly',p:'oh-loo-boo-toh',ic:'🤰'},
{l:'Emikono',e:'Hands (plural)',p:'eh-mee-koh-noh',ic:'🙌'},
{l:'Enva y\'omubiri',e:'Body organs',p:'en-vah yoh-moo-bee-ree',ic:'🫀'},
{l:'Enyama',e:'Flesh / Muscle',p:'eh-nyah-mah',ic:'💪'},
{l:'Omwojo',e:'Finger',p:'ohm-woh-joh',ic:'☝️'},
{l:'Akabenje',e:'Cheek',p:'ah-kah-behn-jeh',ic:'😊'},
{l:'Ekyoya',e:'Wing / Feather',p:'eh-choh-yah',ic:'🪶'},
{l:'Okeya',e:'Elbow',p:'oh-keh-yah',ic:'💪'},
{l:'Empale',e:'Trousers',p:'ehm-pah-leh',ic:'👖'},
{l:'Olugoye lw\'omubiri',e:'Body covering',p:'oh-loo-goh-yeh lwoh-moo-bee-ree',ic:'🧥'},
{l:'Oluggi lw\'okutu',e:'Eardrum',p:'oh-loo-gee lwoh-koo-too',ic:'👂'},
{l:'Okukeera',e:'Fever / Temperature',p:'oh-koo-keh-rah',ic:'🤒'},
{l:'Akabenje',e:'Cheekbone',p:'ah-kah-behn-jeh',ic:'😊'},
{l:'Olubiri',e:'Hip',p:'oh-loo-bee-ree',ic:'🦴'},
{l:'Ensulo',e:'Mucus / Nasal discharge',p:'en-soo-loh',ic:'👃'},
{l:'Ekizimba ky\'omubiri',e:'Body part',p:'eh-kee-zeem-bah choh-moo-bee-ree',ic:'🧍'},
{l:'Obukuumi',e:'Recovery / Healing',p:'oh-boo-koo-mee',ic:'💊'},
{l:'Obutiti',e:'Nervousness / Trembling',p:'oh-boo-tee-tee',ic:'😰'},
{l:'Okuwulira bulungi',e:'Feeling good',p:'oh-koo-woo-lee-rah boo-loon-gee',ic:'😊'},
{l:'Okuwulira bubi',e:'Feeling bad / sick',p:'oh-koo-woo-lee-rah boo-bee',ic:'🤒'},
{l:'Amaanyi',e:'Strength / Energy',p:'ah-mah-nyee',ic:'⚡'},
{l:'Obunafuusi',e:'Weakness / Fatigue',p:'oh-boo-nah-foo-see',ic:'😔'},
{l:'Enkago',e:'Body frame / Build',p:'en-kah-goh',ic:'🧍'},
{l:'Omwoyo',e:'Soul / Spirit',p:'ohm-woh-yoh',ic:'✨'}
],
food:[
{l:'Emmere',e:'Food',p:'eh-meh-reh',ic:'🍽️'},
{l:'Amazzi',e:'Water',p:'ah-mah-zee',ic:'💧'},
{l:'Enva',e:'Vegetables',p:'en-vah',ic:'🥦'},
{l:'Ennyama',e:'Meat',p:'eh-nyah-mah',ic:'🥩'},
{l:'Ebbere',e:'Milk',p:'eh-beh-reh',ic:'🥛'},
{l:'Omugati',e:'Bread',p:'oh-moo-gah-tee',ic:'🍞'},
{l:'Ebitooke',e:'Matoke / Plantain',p:'eh-bee-toh-keh',ic:'🍌'},
{l:'Obutunda',e:'Tomatoes',p:'oh-boo-toon-dah',ic:'🍅'},
{l:'Enjuba',e:'Salt',p:'en-joo-bah',ic:'🧂'},
{l:'Mafuta',e:'Oil',p:'mah-foo-tah',ic:'🫙'},
{l:'Ekyenvu',e:'Groundnut / Peanut',p:'eh-cheh-nvoo',ic:'🥜'},
{l:'Obwali',e:'Millet porridge',p:'oh-bwah-lee',ic:'🥣'},
{l:'Ssukali',e:'Sugar',p:'soo-kah-lee',ic:'🍬'},
{l:'Kaawa',e:'Coffee',p:'kah-wah',ic:'☕'},
{l:'Caayi',e:'Tea',p:'chah-yee',ic:'🫖'},
{l:'Omucungwa',e:'Orange',p:'oh-moo-coon-gwah',ic:'🍊'},
{l:'Emiyembe',e:'Mangoes',p:'eh-mee-yehm-beh',ic:'🥭'},
{l:'Amasanyu',e:'Eggs',p:'ah-mah-sahn-yoo',ic:'🥚'},
{l:'Enkoko',e:'Chicken',p:'en-koh-koh',ic:'🐔'},
{l:'Enjala',e:'Hunger',p:'en-jah-lah',ic:'😫'},
{l:'Emmande',e:'Cassava',p:'eh-mahn-deh',ic:'🌿'},
{l:'Ekijanjaalo',e:'Beans',p:'eh-kee-jahn-jah-loh',ic:'🫘'},
{l:'Kasooli',e:'Maize / Corn',p:'kah-soh-lee',ic:'🌽'},
{l:'Amata',e:'Cow milk',p:'ah-mah-tah',ic:'🥛'},
{l:'Posho',e:'Maize porridge',p:'poh-shoh',ic:'🥣'},
{l:'Ebbugga',e:'Banana',p:'eh-boo-gah',ic:'🍌'},
{l:'Empindi',e:'Pigeon peas',p:'ehm-peen-dee',ic:'🫘'},
{l:'Akawunga',e:'Flour',p:'ah-kah-woon-gah',ic:'🌾'},
{l:'Nkejje',e:'Tilapia fish',p:'n-keh-jeh',ic:'🐟'},
{l:'Enkwanzi',e:'Fish',p:'en-kwahn-zee',ic:'🐠'},
{l:'Enkooge',e:'Groundnut sauce',p:'en-koh-geh',ic:'🥜'},
{l:'Oluwombo',e:'Steamed banana-leaf dish',p:'oh-loo-wohm-boh',ic:'🍲'},
{l:'Akatogo',e:'Mixed vegetable stew',p:'ah-kah-toh-goh',ic:'🍲'},
{l:'Omuzigo',e:'Ghee / Butter',p:'oh-moo-zee-goh',ic:'🧈'},
{l:'Omwenge',e:'Beer / Alcohol',p:'ohm-wehn-geh',ic:'🍺'},
{l:'Okulya',e:'To eat',p:'oh-koo-lyah',ic:'😋'},
{l:'Okunywa',e:'To drink',p:'oh-koon-ywah',ic:'🥤'},
{l:'Enjojo',e:'Yam',p:'en-joh-joh',ic:'🥔'},
{l:'Ekyoto',e:'Kitchen / Fireplace',p:'eh-choh-toh',ic:'🍳'},
{l:'Ekyokyo',e:'Cooking fire',p:'eh-choh-choh',ic:'🔥'},
{l:'Ndimu',e:'Lime / Lemon',p:'n-dee-moo',ic:'🍋'},
{l:'Akabisi',e:'Raw / Uncooked',p:'ah-kah-bee-see',ic:'🥬'},
{l:'Omupiira gw\'emmere',e:'Food pot',p:'oh-moo-pee-rah gweh-meh-reh',ic:'🍲'},
{l:'Omusolo',e:'Tax / Levy',p:'oh-moo-soh-loh',ic:'💰'},
{l:'Ebiryo',e:'Meals / Dishes',p:'eh-bee-ryoh',ic:'🍽️'},
{l:'Ensimbi',e:'Coins / Small money',p:'en-seem-bee',ic:'🪙'},
{l:'Ekibala',e:'Fruit',p:'eh-kee-bah-lah',ic:'🍎'},
{l:'Ensuja',e:'Supper / Evening meal',p:'en-soo-jah',ic:'🌙'},
{l:'Ekyambala',e:'Breakfast',p:'eh-chahm-bah-lah',ic:'🌅'},
{l:'Omuddo',e:'Sauce / Gravy',p:'oh-moo-doh',ic:'🫙'}
],
home:[
{l:'Enju',e:'House / Home',p:'en-joo',ic:'🏠'},
{l:'Oluggya',e:'Compound / Yard',p:'oh-loo-gyah',ic:'🏡'},
{l:'Ekisenge',e:'Room',p:'eh-kee-sehn-geh',ic:'🚪'},
{l:'Oluggi',e:'Door',p:'oh-loo-gee',ic:'🚪'},
{l:'Eddiiro',e:'Sitting room',p:'eh-dee-roh',ic:'🛋️'},
{l:'Bbeddi',e:'Bed',p:'beh-dee',ic:'🛏️'},
{l:'Entebe',e:'Chair',p:'en-teh-beh',ic:'🪑'},
{l:'Emmeeza',e:'Table',p:'eh-meh-zah',ic:'🪞'},
{l:'Ekitabo',e:'Book',p:'eh-kee-tah-boh',ic:'📖'},
{l:'Simu',e:'Phone',p:'see-moo',ic:'📱'},
{l:'Engoye',e:'Clothes',p:'en-goh-yeh',ic:'👕'},
{l:'Engatto',e:'Shoes',p:'en-gah-toh',ic:'👟'},
{l:'Ensawo',e:'Bag',p:'en-sah-woh',ic:'👜'},
{l:'Entobo',e:'Knife',p:'en-toh-boh',ic:'🔪'},
{l:'Nnambooze',e:'Key',p:'nah-m-boh-zeh',ic:'🔑'},
{l:'Omuliro',e:'Fire',p:'oh-moo-lee-roh',ic:'🔥'},
{l:'Ettaala',e:'Lamp / Light',p:'eh-tah-lah',ic:'💡'},
{l:'Endeku',e:'Broom',p:'en-deh-koo',ic:'🧹'},
{l:'Ekyuma',e:'Metal / Tool',p:'eh-choo-mah',ic:'🔧'},
{l:'Olupapula',e:'Paper / Document',p:'oh-loo-pah-poo-lah',ic:'📄'},
{l:'Ensero',e:'Basket',p:'en-seh-roh',ic:'🧺'},
{l:'Olugoye',e:'Cloth / Fabric',p:'oh-loo-goh-yeh',ic:'🧣'},
{l:'Omupiira',e:'Ball',p:'oh-moo-pee-rah',ic:'⚽'},
{l:'Amaanyi',e:'Electricity / Power',p:'ah-mah-nyee',ic:'⚡'},
{l:'Ekisumuluzo',e:'Lock',p:'eh-kee-soo-moo-loo-zoh',ic:'🔒'},
{l:'Ensawo enkulu',e:'Suitcase',p:'en-sah-woh en-koo-loo',ic:'🧳'},
{l:'Olukomera',e:'Stick / Pole',p:'oh-loo-koh-meh-rah',ic:'🪵'},
{l:'Oluwatu',e:'Stone / Rock',p:'oh-loo-wah-too',ic:'🪨'},
{l:'Ettaka',e:'Soil / Land',p:'eh-tah-kah',ic:'🌍'},
{l:'Emmeeri',e:'Boat / Canoe',p:'eh-meh-ree',ic:'⛵'},
{l:'Enkomera',e:'Fence',p:'en-koh-meh-rah',ic:'🏗️'},
{l:'Akasero',e:'Small basket',p:'ah-kah-seh-roh',ic:'🧺'},
{l:'Ekiwandiiko',e:'Writing / Document',p:'eh-kee-wahn-dee-koh',ic:'📄'},
{l:'Olubuutu',e:'Courtyard',p:'oh-loo-boo-too',ic:'🏘️'},
{l:'Ennaka',e:'Field / Garden',p:'eh-nah-kah',ic:'🌾'},
{l:'Akawuka',e:'Insect / Bug',p:'ah-kah-woo-kah',ic:'🐛'},
{l:'Olugya',e:'Outside area',p:'oh-loo-gyah',ic:'🌿'},
{l:'Ennyumba enkulu',e:'Large house',p:'eh-nyoom-bah en-koo-loo',ic:'🏠'},
{l:'Omuliro gw\'omukeeka',e:'Charcoal fire',p:'oh-moo-lee-roh gwoh-moo-keh-kah',ic:'🔥'},
{l:'Ekisenge ky\'okuloga',e:'Bedroom',p:'eh-kee-sehn-geh choh-koo-loh-gah',ic:'🛏️'},
{l:'Omukeeka',e:'Mat / Reed mat',p:'oh-moo-keh-kah',ic:'🛏️'},
{l:'Ensiimbi',e:'Shell / Coin',p:'en-seem-bee',ic:'🪙'},
{l:'Akabina',e:'Small room / Closet',p:'ah-kah-bee-nah',ic:'🚪'},
{l:'Ekyuma ky\'okunywa',e:'Drinking vessel',p:'eh-choo-mah choh-koon-ywah',ic:'🥤'},
{l:'Endabirwamu',e:'Mirror',p:'en-dah-beer-wah-moo',ic:'🪞'},
{l:'Empagi',e:'Pillar / Post',p:'ehm-pah-gee',ic:'🪵'},
{l:'Akasimu',e:'Small phone / Radio',p:'ah-kah-see-moo',ic:'📻'},
{l:'Ekyoya ky\'engoye',e:'Clothes hanger',p:'eh-choh-yah cheh-ngoh-yeh',ic:'👕'},
{l:'Oluggi lw\'ennyumba',e:'House gate',p:'oh-loo-gee lweh-nyoom-bah',ic:'🚪'},
{l:'Ensawo y\'ekitabo',e:'School bag',p:'en-sah-woh yeh-kee-tah-boh',ic:'🎒'}
],
nature:[
{l:'Ennimiro',e:'Garden / Farm',p:'eh-nee-mee-roh',ic:'🌾'},
{l:'Omuti',e:'Tree',p:'oh-moo-tee',ic:'🌳'},
{l:'Ekibira',e:'Forest',p:'eh-kee-bee-rah',ic:'🌲'},
{l:'Enjovu',e:'Elephant',p:'en-joh-voo',ic:'🐘'},
{l:'Empologoma',e:'Lion',p:'ehm-poh-loh-goh-mah',ic:'🦁'},
{l:'Enkima',e:'Monkey',p:'en-kee-mah',ic:'🐒'},
{l:'Embwa',e:'Dog',p:'ehm-bwah',ic:'🐕'},
{l:'Ente',e:'Cow',p:'en-teh',ic:'🐄'},
{l:'Emmeme',e:'Cat',p:'eh-meh-meh',ic:'🐈'},
{l:'Enyonyi',e:'Bird',p:'eh-nyoh-nyee',ic:'🐦'},
{l:'Ennyanja',e:'Lake / Ocean',p:'eh-nyahn-jah',ic:'🌊'},
{l:'Embubi',e:'Goat',p:'ehm-boo-bee',ic:'🐐'},
{l:'Endiga',e:'Sheep',p:'en-dee-gah',ic:'🐑'},
{l:'Enkuba',e:'Rain',p:'en-koo-bah',ic:'🌧️'},
{l:'Empewo',e:'Wind / Air',p:'ehm-peh-woh',ic:'💨'},
{l:'Enjuba',e:'Sun',p:'en-joo-bah',ic:'☀️'},
{l:'Omwezi',e:'Moon',p:'ohm-weh-zee',ic:'🌙'},
{l:'Enswera',e:'Bee',p:'en-sweh-rah',ic:'🐝'},
{l:'Enkwanzi',e:'Fish',p:'en-kwahn-zee',ic:'🐟'},
{l:'Omugga',e:'River',p:'oh-moo-gah',ic:'🏞️'},
{l:'Olusozi',e:'Mountain / Hill',p:'oh-loo-soh-zee',ic:'⛰️'},
{l:'Ekibulanku',e:'Cloud',p:'eh-kee-boo-lahn-koo',ic:'☁️'},
{l:'Engonzi',e:'Rabbit',p:'en-gohn-zee',ic:'🐇'},
{l:'Nkejje',e:'Tilapia fish',p:'n-keh-jeh',ic:'🐠'},
{l:'Enswa',e:'Flying ants (edible)',p:'en-swah',ic:'🐜'},
{l:'Omusana',e:'Sunshine / Warmth',p:'oh-moo-sah-nah',ic:'🌞'},
{l:'Akabonero',e:'Star',p:'ah-kah-boh-neh-roh',ic:'⭐'},
{l:'Olusuku',e:'Banana plantation',p:'oh-loo-soo-koo',ic:'🍌'},
{l:'Ngo',e:'Leopard',p:'ngoh',ic:'🐆'},
{l:'Empisi',e:'Hyena',p:'ehm-pee-see',ic:'🐺'},
{l:'Enjovu enkulu',e:'Hippo',p:'en-joh-voo en-koo-loo',ic:'🦛'},
{l:'Omuddo',e:'Mud / Swamp',p:'oh-moo-doh',ic:'🌊'},
{l:'Ettale',e:'Sunshine / Dry season',p:'eh-tah-leh',ic:'🌤️'},
{l:'Amazzi g\'enkuba',e:'Rainwater',p:'ah-mah-zee gehn-koo-bah',ic:'💧'},
{l:'Nabbubi',e:'Spider',p:'nah-boo-bee',ic:'🕷️'},
{l:'Eddungu',e:'Wilderness / Bush',p:'eh-doon-goo',ic:'🌿'},
{l:'Omuguwa',e:'Rope / Vine',p:'oh-moo-goo-wah',ic:'🌿'},
{l:'Enkoko',e:'Hen / Chicken',p:'en-koh-koh',ic:'🐔'},
{l:'Omuti gw\'emmiyembe',e:'Mango tree',p:'oh-moo-tee gweh-mee-yehm-beh',ic:'🥭'},
{l:'Oluggya lw\'ettaka',e:'Open ground',p:'oh-loo-gyah lweh-tah-kah',ic:'🌍'},
{l:'Obutiko',e:'Mushrooms',p:'oh-boo-tee-koh',ic:'🍄'},
{l:'Entuumu',e:'Mushroom',p:'en-too-moo',ic:'🍄'},
{l:'Akawuka akazibu',e:'Dangerous insect',p:'ah-kah-woo-kah ah-kah-zee-boo',ic:'🐛'},
{l:'Eminyolo',e:'Roots',p:'eh-meen-yoh-loh',ic:'🌱'},
{l:'Entandikwa',e:'Seedling',p:'en-tahn-dee-kwah',ic:'🌱'},
{l:'Olunyiriri',e:'Row / Line of trees',p:'oh-loo-nyee-ree-ree',ic:'🌳'},
{l:'Amazzi amabi',e:'Dirty water',p:'ah-mah-zee ah-mah-bee',ic:'🌊'},
{l:'Amazzi amalungi',e:'Clean water',p:'ah-mah-zee ah-mah-loon-gee',ic:'💧'},
{l:'Olutindo lw\'omugga',e:'River bank',p:'oh-loo-teen-doh lwoh-moo-gah',ic:'🏞️'},
{l:'Ekibira ekinene',e:'Dense forest',p:'eh-kee-bee-rah eh-kee-neh-neh',ic:'🌲'}
],
numbers:[
{l:'Emu',e:'One',p:'eh-moo',ic:'1️⃣'},
{l:'Bbiri',e:'Two',p:'bee-ree',ic:'2️⃣'},
{l:'Ssatu',e:'Three',p:'sah-too',ic:'3️⃣'},
{l:'Nnya',e:'Four',p:'nyah',ic:'4️⃣'},
{l:'Ttaano',e:'Five',p:'tah-noh',ic:'5️⃣'},
{l:'Mukaaga',e:'Six',p:'moo-kah-gah',ic:'6️⃣'},
{l:'Musanvu',e:'Seven',p:'moo-sahn-voo',ic:'7️⃣'},
{l:'Munaana',e:'Eight',p:'moo-nah-nah',ic:'8️⃣'},
{l:'Mwenda',e:'Nine',p:'mwehn-dah',ic:'9️⃣'},
{l:'Kkumi',e:'Ten',p:'koo-mee',ic:'🔟'},
{l:'Kkumi n\'emu',e:'Eleven',p:'koo-mee neh-moo',ic:'1️⃣'},
{l:'Kkumi na bbiri',e:'Twelve',p:'koo-mee nah bee-ree',ic:'2️⃣'},
{l:'Kkumi na ssatu',e:'Thirteen',p:'koo-mee nah sah-too',ic:'3️⃣'},
{l:'Makumi abiri',e:'Twenty',p:'mah-koo-mee ah-bee-ree',ic:'✌️'},
{l:'Makumi asatu',e:'Thirty',p:'mah-koo-mee ah-sah-too',ic:'3️⃣'},
{l:'Makumi ana',e:'Forty',p:'mah-koo-mee ah-nah',ic:'4️⃣'},
{l:'Makumi ataano',e:'Fifty',p:'mah-koo-mee ah-tah-noh',ic:'5️⃣'},
{l:'Kikumi',e:'One hundred',p:'kee-koo-mee',ic:'💯'},
{l:'Lukumi',e:'One thousand',p:'loo-koo-mee',ic:'🔢'},
{l:'Sawa',e:'Hour / Time',p:'sah-wah',ic:'⏰'},
{l:'Olunaku',e:'Day',p:'oh-loo-nah-koo',ic:'📅'},
{l:'Wiiki',e:'Week',p:'wee-kee',ic:'📆'},
{l:'Omwezi',e:'Month',p:'ohm-weh-zee',ic:'📅'},
{l:'Omwaka',e:'Year',p:'ohm-wah-kah',ic:'🎆'},
{l:'Kaakati',e:'Now / At this moment',p:'kah-kah-tee',ic:'⏱️'},
{l:'Leero',e:'Today',p:'leh-roh',ic:'📆'},
{l:'Enkya',e:'Tomorrow',p:'en-chah',ic:'➡️'},
{l:'Ggulo',e:'Yesterday',p:'goo-loh',ic:'⬅️'},
{l:'Ekiro',e:'Night',p:'eh-kee-roh',ic:'🌙'},
{l:'Entuntu',e:'Morning',p:'en-toon-too',ic:'🌅'},
{l:'Omukaaga',e:'Evening / 6 o\'clock',p:'oh-moo-kah-gah',ic:'🌆'},
{l:'Enkya enkya',e:'Day after tomorrow',p:'en-chah en-chah',ic:'⏭️'},
{l:'Ggulo ggulo',e:'Day before yesterday',p:'goo-loh goo-loh',ic:'⏮️'},
{l:'Sabbiiti',e:'Sunday',p:'sah-bee-tee',ic:'📅'},
{l:'Bbalaza',e:'Monday',p:'bah-lah-zah',ic:'📅'},
{l:'Lwakubiri',e:'Tuesday',p:'lwah-koo-bee-ree',ic:'📅'},
{l:'Olwokusatu',e:'Wednesday',p:'oh-lwoh-koo-sah-too',ic:'📅'},
{l:'Olwokuna',e:'Thursday',p:'oh-lwoh-koo-nah',ic:'📅'},
{l:'Olwokuttaano',e:'Friday',p:'oh-lwoh-koo-tah-noh',ic:'📅'},
{l:'Lwamukaaga',e:'Saturday',p:'lwah-moo-kah-gah',ic:'📅'},
{l:'Mu maaso',e:'In the future / Ahead',p:'moo mah-soh',ic:'⏩'},
{l:'Ennuma',e:'Behind / In the past',p:'eh-noo-mah',ic:'⏪'},
{l:'Amaka',e:'Home time / Household',p:'ah-mah-kah',ic:'🏠'},
{l:'Ssawa mmeka',e:'What time is it?',p:'sah-wah meh-kah',ic:'⏰'},
{l:'Ku ssawa',e:'At (the hour)',p:'koo sah-wah',ic:'⌚'},
{l:'Obucuucu',e:'Midnight',p:'oh-boo-choo-choo',ic:'🌑'},
{l:'Okusooka',e:'First / To come first',p:'oh-koo-soh-kah',ic:'🥇'},
{l:'Okumalirizaako',e:'Last / To finish last',p:'oh-koo-mah-lee-ree-zah-koh',ic:'🏁'},
{l:'Emirundi emeka',e:'How many times?',p:'eh-mee-roon-dee eh-meh-kah',ic:'🔢'},
{l:'Emirundi ebiri',e:'Twice',p:'eh-mee-roon-dee eh-bee-ree',ic:'2️⃣'},
{l:'Buli lunaku',e:'Every day',p:'boo-lee loo-nah-koo',ic:'📅'}
],
verbs:[
{l:'Okugenda',e:'To go',p:'oh-koo-gehn-dah',ic:'🚶'},
{l:'Okujja',e:'To come',p:'oh-koo-jah',ic:'🏃'},
{l:'Okutuuka',e:'To arrive',p:'oh-koo-too-kah',ic:'🏁'},
{l:'Okulya',e:'To eat',p:'oh-koo-lyah',ic:'🍽️'},
{l:'Okunywa',e:'To drink',p:'oh-koon-ywah',ic:'🥤'},
{l:'Okuloga',e:'To sleep',p:'oh-koo-loh-gah',ic:'😴'},
{l:'Okudduka',e:'To run',p:'oh-koo-doo-kah',ic:'🏃'},
{l:'Okusoma',e:'To read / study',p:'oh-koo-soh-mah',ic:'📖'},
{l:'Okugula',e:'To buy',p:'oh-koo-goo-lah',ic:'🛒'},
{l:'Okuwa',e:'To give',p:'oh-koo-wah',ic:'🎁'},
{l:'Okukola',e:'To work / do',p:'oh-koo-koh-lah',ic:'⚒️'},
{l:'Okwogera',e:'To speak',p:'oh-kwoh-geh-rah',ic:'🗣️'},
{l:'Okulaba',e:'To see',p:'oh-koo-lah-bah',ic:'👁️'},
{l:'Okuwulira',e:'To hear / feel',p:'oh-koo-woo-lee-rah',ic:'👂'},
{l:'Okutambula',e:'To walk / travel',p:'oh-koo-tahm-boo-lah',ic:'🚶'},
{l:'Okwagala',e:'To love / want',p:'oh-kwah-gah-lah',ic:'❤️'},
{l:'Okufumba',e:'To cook',p:'oh-koo-foom-bah',ic:'🍳'},
{l:'Okunaaba',e:'To bathe / wash',p:'oh-koo-nah-bah',ic:'🚿'},
{l:'Okuzina',e:'To dance',p:'oh-koo-zee-nah',ic:'💃'},
{l:'Okuyimba',e:'To sing',p:'oh-koo-yeem-bah',ic:'🎵'},
{l:'Okuseka',e:'To laugh',p:'oh-koo-seh-kah',ic:'😂'},
{l:'Okutandika',e:'To begin / start',p:'oh-koo-tahn-dee-kah',ic:'▶️'},
{l:'Okumaliriza',e:'To finish',p:'oh-koo-mah-lee-ree-zah',ic:'✅'},
{l:'Okuyamba',e:'To help',p:'oh-koo-yahm-bah',ic:'🤝'},
{l:'Okulowooza',e:'To think',p:'oh-koo-loh-woh-zah',ic:'🤔'},
{l:'Okujukira',e:'To remember',p:'oh-koo-joo-kee-rah',ic:'🧠'},
{l:'Okutya',e:'To fear',p:'oh-koo-tyah',ic:'😨'},
{l:'Okusigala',e:'To remain / stay',p:'oh-koo-see-gah-lah',ic:'🏠'},
{l:'Okufuluma',e:'To exit / go out',p:'oh-koo-foo-loo-mah',ic:'🚪'},
{l:'Okuyingira',e:'To enter',p:'oh-koo-yeen-gee-rah',ic:'🚪'},
{l:'Okusanga',e:'To find / meet',p:'oh-koo-sahn-gah',ic:'🔍'},
{l:'Okutuula',e:'To sit',p:'oh-koo-too-lah',ic:'🪑'},
{l:'Okwimirira',e:'To stand',p:'oh-kwee-mee-ree-rah',ic:'🧍'},
{l:'Okutema',e:'To cut / chop',p:'oh-koo-teh-mah',ic:'🪓'},
{l:'Okulima',e:'To cultivate / farm',p:'oh-koo-lee-mah',ic:'🌾'},
{l:'Okusomesa',e:'To teach',p:'oh-koo-soh-meh-sah',ic:'👩‍🏫'},
{l:'Okukkiriza',e:'To agree / believe',p:'oh-koo-kee-ree-zah',ic:'✅'},
{l:'Okusasula',e:'To pay',p:'oh-koo-sah-soo-lah',ic:'💸'},
{l:'Okutunda',e:'To sell',p:'oh-koo-toon-dah',ic:'🏪'},
{l:'Okuzimba',e:'To build',p:'oh-koo-zeem-bah',ic:'🏗️'},
{l:'Okugwa',e:'To fall',p:'oh-koo-gwah',ic:'⬇️'},
{l:'Okusaba',e:'To pray / beg',p:'oh-koo-sah-bah',ic:'🙏'},
{l:'Okubuuza',e:'To ask',p:'oh-koo-boo-zah',ic:'❓'},
{l:'Okubuuka',e:'To fly / jump up',p:'oh-koo-boo-kah',ic:'🦅'},
{l:'Okusitula',e:'To lift / carry',p:'oh-koo-see-too-lah',ic:'🏋️'},
{l:'Okukuuma',e:'To protect',p:'oh-koo-koo-mah',ic:'🛡️'},
{l:'Okufuna',e:'To receive / get',p:'oh-koo-foo-nah',ic:'🤲'},
{l:'Okuddamu',e:'To reply / return',p:'oh-koo-dah-moo',ic:'↩️'},
{l:'Okukwata',e:'To hold / catch',p:'oh-koo-kwah-tah',ic:'✊'},
{l:'Okusiima',e:'To thank / appreciate',p:'oh-koo-see-mah',ic:'🙏'},
{l:'Okutegeera',e:'To understand',p:'oh-koo-teh-geh-rah',ic:'💡'},
{l:'Okweyamba',e:'To help oneself',p:'oh-kweh-yahm-bah',ic:'💪'},
{l:'Okufuuka',e:'To become',p:'oh-koo-foo-kah',ic:'🔄'},
{l:'Okuba',e:'To be',p:'oh-koo-bah',ic:'🌱'},
{l:'Okukyusa',e:'To change',p:'oh-koo-choo-sah',ic:'🔄'},
{l:'Okugaana',e:'To refuse / deny',p:'oh-koo-gah-nah',ic:'🚫'},
{l:'Okunyumirwa',e:'To enjoy / be happy',p:'oh-koo-nyoo-meer-wah',ic:'😊'},
{l:'Okugoba',e:'To chase away',p:'oh-koo-goh-bah',ic:'🏃'},
{l:'Okusirika',e:'To be quiet / silent',p:'oh-koo-see-ree-kah',ic:'🤫'},
{l:'Okukaabirira',e:'To shout',p:'oh-koo-kah-bee-ree-rah',ic:'📢'},
{l:'Okukungubaga',e:'To whisper',p:'oh-koo-koon-goo-bah-gah',ic:'🤫'},
{l:'Okwetaba',e:'To participate',p:'oh-kweh-tah-bah',ic:'🙋'},
{l:'Okufubirwa',e:'To be tired',p:'oh-koo-foo-beer-wah',ic:'😴'},
{l:'Okusasirira',e:'To be angry',p:'oh-koo-sah-see-ree-rah',ic:'😠'},
{l:'Okwebaka',e:'To lie down / rest',p:'oh-kweh-bah-kah',ic:'🛏️'},
{l:'Okuvvuka',e:'To cross over',p:'oh-koo-voo-kah',ic:'🌉'},
{l:'Okukozesa',e:'To use',p:'oh-koo-koh-zeh-sah',ic:'🛠️'},
{l:'Okusabira',e:'To pray for',p:'oh-koo-sah-bee-rah',ic:'🙏'},
{l:'Okwoleseza',e:'To show / demonstrate',p:'oh-kwoh-leh-seh-zah',ic:'👆'},
{l:'Okutuusa',e:'To deliver / reach',p:'oh-koo-too-sah',ic:'📬'},
{l:'Okuvuma',e:'To scold / rebuke',p:'oh-koo-voo-mah',ic:'😤'},
{l:'Okwebaza',e:'To thank / praise',p:'oh-kweh-bah-zah',ic:'🙌'},
{l:'Okunoonyeza',e:'To investigate',p:'oh-koo-noh-nyeh-zah',ic:'🔍'},
{l:'Okukubiriza',e:'To encourage',p:'oh-koo-koo-bee-ree-zah',ic:'💪'},
{l:'Okubuulira',e:'To tell / inform',p:'oh-koo-boo-lee-rah',ic:'📢'},
{l:'Okuwandiika',e:'To write',p:'oh-koo-wahn-dee-kah',ic:'✍️'},
{l:'Okwongera',e:'To add / increase',p:'oh-kwohn-geh-rah',ic:'➕'},
{l:'Okukendeeza',e:'To reduce / decrease',p:'oh-koo-kehn-deh-zah',ic:'➖'},
{l:'Okuzaala',e:'To give birth',p:'oh-koo-zah-lah',ic:'👶'},
{l:'Okufa',e:'To die',p:'oh-koo-fah',ic:'🕊️'},
{l:'Okuzaalwa',e:'To be born',p:'oh-koo-zah-lwah',ic:'🌱'},
{l:'Okukulira',e:'To grow up',p:'oh-koo-koo-lee-rah',ic:'📈'},
{l:'Okugolola',e:'To straighten / correct',p:'oh-koo-goh-loh-lah',ic:'✏️'},
{l:'Okunyweza',e:'To water plants',p:'oh-koon-yweh-zah',ic:'🌱'},
{l:'Okwetaaga',e:'To need / require',p:'oh-kweh-tah-gah',ic:'🙏'},
{l:'Okukyawa',e:'To hate / dislike',p:'oh-koo-chah-wah',ic:'😤'},
{l:'Okukolagana',e:'To work together',p:'oh-koo-koh-lah-gah-nah',ic:'🤝'},
{l:'Okuteebereza',e:'To plan / prepare',p:'oh-koo-teh-beh-reh-zah',ic:'📋'},
{l:'Okunagula',e:'To wash clothes',p:'oh-koo-nah-goo-lah',ic:'👕'},
{l:'Okusasura',e:'To sweep',p:'oh-koo-sah-soo-rah',ic:'🧹'},
{l:'Okusala',e:'To cut (hair/cloth)',p:'oh-koo-sah-lah',ic:'✂️'},
{l:'Okubiika',e:'To store / save',p:'oh-koo-bee-kah',ic:'📦'},
{l:'Okusindika',e:'To push / send',p:'oh-koo-seen-dee-kah',ic:'📤'},
{l:'Okutereza',e:'To prepare things',p:'oh-koo-teh-reh-zah',ic:'📋'},
{l:'Okwetegereza',e:'To pay attention',p:'oh-kweh-teh-geh-reh-zah',ic:'🎯'},
{l:'Okwekebalira',e:'To be patient',p:'oh-kweh-keh-bah-lee-rah',ic:'🕊️'},
{l:'Okugalagala',e:'To wander / roam',p:'oh-koo-gah-lah-gah-lah',ic:'🚶'},
{l:'Okwebuuza',e:'To wonder / ask oneself',p:'oh-kweh-boo-zah',ic:'🤔'},
{l:'Okulabika',e:'To appear / be visible',p:'oh-koo-lah-bee-kah',ic:'👁️'},
{l:'Okukuba',e:'To beat / knock',p:'oh-koo-koo-bah',ic:'👊'},
{l:'Okuteeka',e:'To put / place',p:'oh-koo-teh-kah',ic:'📦'},
{l:'Okuggyamu',e:'To remove / take out',p:'oh-koo-gyah-moo',ic:'↩️'},
{l:'Okwebakira',e:'To sleep on it / rest',p:'oh-kweh-bah-kee-rah',ic:'💤'}
],
adjectives:[
{l:'Bulungi',e:'Good / Beautiful',p:'boo-loon-gee',ic:'✨'},
{l:'Bubi',e:'Bad',p:'boo-bee',ic:'👎'},
{l:'Kinene',e:'Big / Large',p:'kee-neh-neh',ic:'🐘'},
{l:'Katono',e:'Small',p:'kah-toh-noh',ic:'🐜'},
{l:'Mpola',e:'Slowly / Gently',p:'m-poh-lah',ic:'🐢'},
{l:'Mangu',e:'Quickly / Fast',p:'mahn-goo',ic:'⚡'},
{l:'Mazima',e:'True / Real',p:'mah-zee-mah',ic:'✅'},
{l:'Kabisi',e:'Very / Extremely',p:'kah-bee-see',ic:'💯'},
{l:'Nyo',e:'Very (emphasis)',p:'nyoh',ic:'‼️'},
{l:'Eddugavu',e:'Black / Dark',p:'eh-doo-gah-voo',ic:'⬛'},
{l:'Myufu',e:'White',p:'myoo-foo',ic:'⬜'},
{l:'Kiggya',e:'New',p:'kee-gyah',ic:'🆕'},
{l:'Kadde',e:'Old',p:'kah-deh',ic:'📜'},
{l:'Mugumu',e:'Hard / Tough',p:'moo-goo-moo',ic:'💎'},
{l:'Woomi',e:'Soft',p:'woh-mee',ic:'🧸'},
{l:'Mwerevu',e:'Clever / Smart',p:'mweh-reh-voo',ic:'🧠'},
{l:'Musiru',e:'Foolish',p:'moo-see-roo',ic:'🤪'},
{l:'Muggagga',e:'Rich / Wealthy',p:'moo-gah-gah',ic:'💰'},
{l:'Mwavu',e:'Poor',p:'mwah-voo',ic:'😔'},
{l:'Mugabi',e:'Generous',p:'moo-gah-bee',ic:'🎁'},
{l:'Nyooma',e:'Sweet',p:'nyoh-mah',ic:'🍬'},
{l:'Kayivu',e:'Lazy',p:'kah-yee-voo',ic:'😴'},
{l:'Kakalu',e:'Difficult / Hard',p:'kah-kah-loo',ic:'😤'},
{l:'Kawanvu',e:'Tall / Long',p:'kah-wahn-voo',ic:'🦒'},
{l:'Mulamu',e:'Alive / Healthy',p:'moo-lah-moo',ic:'🌱'},
{l:'Yenna',e:'All / Everyone',p:'yeh-nah',ic:'🌐'},
{l:'Kiragala',e:'Bright / Clear',p:'kee-rah-gah-lah',ic:'☀️'},
{l:'Kirimu',e:'Dark / Gloomy',p:'kee-ree-moo',ic:'🌑'},
{l:'Mpola mpola',e:'Gradually',p:'m-poh-lah m-poh-lah',ic:'🐌'},
{l:'Tewali',e:'There is none',p:'teh-wah-lee',ic:'❌'},
{l:'Waliwo',e:'There is',p:'wah-lee-woh',ic:'✔️'},
{l:'Mukutu',e:'Fat / Thick',p:'moo-koo-too',ic:'🐘'},
{l:'Mupeke',e:'Thin / Slim',p:'moo-peh-keh',ic:'🪶'},
{l:'Obulungi',e:'Beauty / Goodness',p:'oh-boo-loon-gee',ic:'🌸'},
{l:'Obubi',e:'Badness / Evil',p:'oh-boo-bee',ic:'🌑'},
{l:'Omulembe',e:'Era / Peace',p:'oh-moo-lehm-beh',ic:'🕊️'},
{l:'Omulungi',e:'Beautiful person',p:'oh-moo-loon-gee',ic:'😍'},
{l:'Omubi',e:'Ugly / Bad person',p:'oh-moo-bee',ic:'😤'},
{l:'Muzito',e:'Heavy / Important',p:'moo-zee-toh',ic:'⚖️'},
{l:'Mwangu',e:'Light / Easy',p:'mwahn-goo',ic:'🪶'},
{l:'Omuyisa',e:'Thin (person)',p:'oh-moo-yee-sah',ic:'🪶'},
{l:'Omufunze',e:'Healthy / Strong',p:'oh-moo-foon-zeh',ic:'💪'},
{l:'Omufufu',e:'Weak / Frail',p:'oh-moo-foo-foo',ic:'😔'},
{l:'Kasookedde',e:'Hungry',p:'kah-soh-keh-deh',ic:'😫'},
{l:'Engira ennungi',e:'Good way / Correct path',p:'en-gee-rah eh-noon-gee',ic:'✅'},
{l:'Buli kimu',e:'Each one / Every single',p:'boo-lee kee-moo',ic:'🔢'},
{l:'Era',e:'And / Also',p:'eh-rah',ic:'➕'},
{l:'Wano',e:'Here',p:'wah-noh',ic:'📍'},
{l:'Eyo',e:'There',p:'eh-yoh',ic:'👉'},
{l:'Ennyo',e:'Very much',p:'eh-nyoh',ic:'💯'},
{l:'Kapanda',e:'Short / Low',p:'kah-pahn-dah',ic:'🐛'}
],
places:[
{l:'Kampala',e:'Capital of Uganda',p:'kahm-pah-lah',ic:'🏙️'},
{l:'Uganda',e:'Uganda',p:'oo-gahn-dah',ic:'🇺🇬'},
{l:'Eddwaliro',e:'Hospital',p:'eh-dwah-lee-roh',ic:'🏥'},
{l:'Ssomero',e:'School',p:'soh-meh-roh',ic:'🏫'},
{l:'Ekklesiya',e:'Church',p:'eh-kleh-see-yah',ic:'⛪'},
{l:'Misikiti',e:'Mosque',p:'mee-see-kee-tee',ic:'🕌'},
{l:'Makiro',e:'Market',p:'mah-kee-roh',ic:'🛒'},
{l:'Ennyanja',e:'Lake / Ocean',p:'eh-nyahn-jah',ic:'🌊'},
{l:'Olusozi',e:'Mountain / Hill',p:'oh-loo-soh-zee',ic:'⛰️'},
{l:'Oluguudo',e:'Road / Street',p:'oh-loo-goo-doh',ic:'🛣️'},
{l:'Ekibuga',e:'Town / City',p:'eh-kee-boo-gah',ic:'🏙️'},
{l:'Ekyalo',e:'Village',p:'eh-chah-loh',ic:'🏡'},
{l:'Ensi',e:'Country / Earth',p:'en-see',ic:'🌍'},
{l:'Lubiri',e:'Palace',p:'loo-bee-ree',ic:'🏰'},
{l:'Boda-boda',e:'Motorcycle taxi',p:'boh-dah boh-dah',ic:'🛵'},
{l:'Ettaxi',e:'Minibus taxi',p:'eh-tah-ksee',ic:'🚌'},
{l:'Entebbe',e:'Entebbe city',p:'en-teh-beh',ic:'✈️'},
{l:'Jinja',e:'Jinja city',p:'jeen-jah',ic:'🌊'},
{l:'Omusimo',e:'Bridge',p:'oh-moo-see-moh',ic:'🌉'},
{l:'Omukutu',e:'Road / Path',p:'oh-moo-koo-too',ic:'🛤️'},
{l:'Gavumenti',e:'Government',p:'gah-voo-mehn-tee',ic:'🏛️'},
{l:'Ssaza',e:'County',p:'sah-zah',ic:'🗺️'},
{l:'Ggombolola',e:'Sub-county',p:'gohm-boh-loh-lah',ic:'📍'},
{l:'Ennyumba',e:'Building / House',p:'eh-nyoom-bah',ic:'🏢'},
{l:'Ekivuyo',e:'Bus station',p:'eh-kee-voo-yoh',ic:'🚉'},
{l:'Masaka',e:'Masaka city',p:'mah-sah-kah',ic:'🏘️'},
{l:'Mbarara',e:'Mbarara city',p:'m-bah-rah-rah',ic:'🏙️'},
{l:'Gulu',e:'Gulu city',p:'goo-loo',ic:'🏙️'},
{l:'Entebbe gy\'enjegere',e:'Airport',p:'en-teh-beh gyeh-njeh-geh-reh',ic:'✈️'},
{l:'Amasomero',e:'Schools',p:'ah-mah-soh-meh-roh',ic:'🎓'},
{l:'Ddungu',e:'Wilderness / Open land',p:'doon-goo',ic:'🌿'},
{l:'Amataba',e:'Stairs / Steps',p:'ah-mah-tah-bah',ic:'🪜'},
{l:'Oluggya olukutu',e:'Main road',p:'oh-loo-gyah oh-loo-koo-too',ic:'🛣️'},
{l:'Ekizimbe',e:'Building / Structure',p:'eh-kee-zeem-beh',ic:'🏗️'},
{l:'Olupapula lw\'ensi',e:'Map',p:'oh-loo-pah-poo-lah lwen-see',ic:'🗺️'},
{l:'Omwonyo',e:'Harbour / Pier',p:'ohm-woh-nyoh',ic:'⚓'},
{l:'Omulamwa',e:'Border / Boundary',p:'oh-moo-lahm-wah',ic:'⛩️'},
{l:'Engeri y\'okugenda',e:'Direction / Route',p:'en-geh-ree yoh-koo-gehn-dah',ic:'🧭'},
{l:'Ekizindalo',e:'Landmark',p:'eh-kee-zeen-dah-loh',ic:'🏛️'},
{l:'Emirembe',e:'Mengo / Peace hills',p:'eh-mee-rehm-beh',ic:'🏰'},
{l:'Namirembe',e:'Namirembe hill',p:'nah-mee-rehm-beh',ic:'⛪'},
{l:'Kibuli',e:'Kibuli (mosque area)',p:'kee-boo-lee',ic:'🕌'},
{l:'Entebbe Rd',e:'Entebbe Road',p:'en-teh-beh rohd',ic:'🛣️'},
{l:'Owino',e:'Owino market',p:'oh-wee-noh',ic:'🛒'},
{l:'Nakasero',e:'Nakasero hill',p:'nah-kah-seh-roh',ic:'🏙️'},
{l:'Kololo',e:'Kololo area',p:'koh-loh-loh',ic:'🏘️'},
{l:'Katwe',e:'Katwe area',p:'kaht-weh',ic:'🏘️'},
{l:'Ekibuga ky\'obukuumi',e:'Health centre',p:'eh-kee-boo-gah choh-boo-koo-mee',ic:'🏥'},
{l:'Ssomero ery\'amaanyi',e:'University',p:'soh-meh-roh eh-ryah-mah-nyee',ic:'🎓'},
{l:'Omusulo',e:'Slope / Hillside',p:'oh-moo-soo-loh',ic:'⛰️'}
],
society:[
{l:'Obwakabaka',e:'Kingship / Monarchy',p:'oh-bwah-kah-bah-kah',ic:'👑'},
{l:'Ekika',e:'Clan',p:'eh-kee-kah',ic:'🧬'},
{l:'Amagezi',e:'Knowledge / Wisdom',p:'ah-mah-geh-zee',ic:'🧠'},
{l:'Empisa',e:'Customs / Manners',p:'ehm-pee-sah',ic:'🎭'},
{l:'Amateeka',e:'Law / Rules',p:'ah-mah-teh-kah',ic:'⚖️'},
{l:'Ekisaawe',e:'Celebration / Festival',p:'eh-kee-sah-weh',ic:'🎉'},
{l:'Ssente',e:'Money',p:'seh-nteh',ic:'💰'},
{l:'Obugagga',e:'Wealth / Riches',p:'oh-boo-gah-gah',ic:'💎'},
{l:'Empaka',e:'Competition',p:'ehm-pah-kah',ic:'🏆'},
{l:'Olukiiko',e:'Council / Meeting',p:'oh-loo-kee-koh',ic:'🏛️'},
{l:'Ekitiibwa',e:'Respect / Honor',p:'eh-kee-tee-bwah',ic:'🎖️'},
{l:'Obwesigwa',e:'Trust / Reliability',p:'oh-bweh-see-gwah',ic:'🤝'},
{l:'Obufumbo',e:'Marriage',p:'oh-boo-foom-boh',ic:'💍'},
{l:'Obuganzi',e:'Love / Affection',p:'oh-boo-gahn-zee',ic:'💞'},
{l:'Enzikiriza',e:'Faith / Belief',p:'en-zee-kee-ree-zah',ic:'🙏'},
{l:'Oluwangula',e:'Freedom',p:'oh-loo-wahn-goo-lah',ic:'🕊️'},
{l:'Obwenkanya',e:'Equality',p:'oh-bwehn-kahn-yah',ic:'⚖️'},
{l:'Emipiiya',e:'Coins / Currency',p:'eh-mee-pee-yah',ic:'🪙'},
{l:'Amazima',e:'Truth / Facts',p:'ah-mah-zee-mah',ic:'💯'},
{l:'Omukwano',e:'Friendship',p:'oh-moo-kwah-noh',ic:'❤️'},
{l:'Obutonde',e:'Patience / Humility',p:'oh-boo-tohn-deh',ic:'🕊️'},
{l:'Enkulakulana',e:'Development',p:'en-koo-lah-koo-lah-nah',ic:'📈'},
{l:'Obwavu',e:'Poverty',p:'oh-bwah-voo',ic:'😔'},
{l:'Endagaano',e:'Agreement / Covenant',p:'en-dah-gah-noh',ic:'📜'},
{l:'Oluganda',e:'Brotherhood / Kinship',p:'oh-loo-gahn-dah',ic:'🤝'},
{l:'Obulimu',e:'Employment / Work',p:'oh-boo-lee-moo',ic:'💼'},
{l:'Emisango',e:'Laws / Court cases',p:'eh-mee-sahn-goh',ic:'⚖️'},
{l:'Omubaka',e:'Ambassador / Messenger',p:'oh-moo-bah-kah',ic:'📨'},
{l:'Amasaza',e:'Counties',p:'ah-mah-sah-zah',ic:'🗺️'},
{l:'Enkola',e:'Method / Style',p:'en-koh-lah',ic:'🎨'},
{l:'Obuwangwa',e:'Nationality',p:'oh-boo-wahn-gwah',ic:'🌍'},
{l:'Eby\'obufuzi',e:'Politics / Governance',p:'eh-byoh-boo-foo-zee',ic:'🏛️'},
{l:'Obukade',e:'Old age',p:'oh-boo-kah-deh',ic:'🧓'},
{l:'Obuto',e:'Youth / Childhood',p:'oh-boo-toh',ic:'👶'},
{l:'Engule',e:'Crown',p:'en-goo-leh',ic:'👑'},
{l:'Akawungeezi',e:'Helper / Assistant',p:'ah-kah-woon-geh-zee',ic:'🤝'},
{l:'Emisango gy\'obufuzi',e:'Political laws',p:'eh-mee-sahn-goh gyoh-boo-foo-zee',ic:'⚖️'},
{l:'Obugagga bw\'ensi',e:'National wealth',p:'oh-boo-gah-gah bwen-see',ic:'💎'},
{l:'Ebyafaayo',e:'History',p:'eh-byah-fah-yoh',ic:'📜'},
{l:'Entalo',e:'War / Battle',p:'en-tah-loh',ic:'⚔️'},
{l:'Emirembe',e:'Peace / Peaceful times',p:'eh-mee-rehm-beh',ic:'🕊️'},
{l:'Obwami',e:'Chieftaincy',p:'oh-bwah-mee',ic:'👑'},
{l:'Ekisumuluzo',e:'Solution / Key',p:'eh-kee-soo-moo-loo-zoh',ic:'🔑'},
{l:'Omulimu gw\'gavumenti',e:'Government job',p:'oh-moo-lee-moo gwah-gah-voo-mehn-tee',ic:'💼'},
{l:'Ekitundu',e:'Region / Area',p:'eh-kee-toon-doo',ic:'🗺️'},
{l:'Obwesimbu',e:'Responsibility',p:'oh-bweh-seem-boo',ic:'📋'},
{l:'Abantu ab\'ensi',e:'Citizens',p:'ah-bahn-too ah-ben-see',ic:'👥'},
{l:'Okukulakulana',e:'Development / To develop',p:'oh-koo-koo-lah-koo-lah-nah',ic:'📈'},
{l:'Obusobozi',e:'Ability / Capacity',p:'oh-boo-soh-boh-zee',ic:'💪'},
{l:'Ekitibwa',e:'Glory / Fame',p:'eh-kee-tee-bwah',ic:'🌟'}
],
questions:[
{l:'Ani',e:'Who?',p:'ah-nee',ic:'❓'},
{l:'Ki',e:'What?',p:'kee',ic:'🤔'},
{l:'Wa',e:'Where?',p:'wah',ic:'📍'},
{l:'Lwaki',e:'Why?',p:'lwah-kee',ic:'🤔'},
{l:'Ngamba',e:'How?',p:'ngahm-bah',ic:'💬'},
{l:'Mmeka',e:'How many?',p:'meh-kah',ic:'🔢'},
{l:'Oba',e:'Or / Maybe',p:'oh-bah',ic:'🤷'},
{l:'Naye',e:'But',p:'nah-yeh',ic:'↩️'},
{l:'Kuba',e:'Because',p:'koo-bah',ic:'💭'},
{l:'Kyokka',e:'Only / Just',p:'choh-kah',ic:'1️⃣'},
{l:'Bwokuba',e:'If',p:'bwoh-koo-bah',ic:'🔀'},
{l:'Era',e:'And / Also',p:'eh-rah',ic:'➕'},
{l:'Ne',e:'And / With',p:'neh',ic:'➕'},
{l:'Mu',e:'In / At',p:'moo',ic:'📍'},
{l:'Ekibuuzo',e:'Question',p:'eh-kee-boo-zoh',ic:'❓'},
{l:'Akasiimo',e:'Answer',p:'ah-kah-see-moh',ic:'💬'},
{l:'Ensonga',e:'Reason / Matter',p:'en-sohn-gah',ic:'💡'},
{l:'Kubanga',e:'Because / Since',p:'koo-bahn-gah',ic:'🔗'},
{l:'Kyebaana',e:'That is why',p:'cheh-bah-nah',ic:'👉'},
{l:'Oyo',e:'That one',p:'oh-yoh',ic:'👆'},
{l:'Kino',e:'This thing',p:'kee-noh',ic:'👇'},
{l:'Wadde',e:'Even though',p:'wah-deh',ic:'🔄'},
{l:'Noolwekyo',e:'Therefore',p:'noh-lweh-choh',ic:'💡'},
{l:'Nga',e:'Like / As',p:'ngah',ic:'🔄'},
{l:'Nti',e:'That (reported speech)',p:'n-tee',ic:'💬'},
{l:'Edda',e:'When? (past)',p:'eh-dah',ic:'⏰'},
{l:'Ludda',e:'When? (future)',p:'loo-dah',ic:'🔮'},
{l:'Wuuno',e:'Right now',p:'woo-noh',ic:'⏱️'},
{l:'Bwatyo',e:'In this way',p:'bwah-tyoh',ic:'👇'},
{l:'Ng\'ako',e:'So / Like that',p:'ngah-koh',ic:'👆'},
{l:'Mu ngeri ki',e:'In what way?',p:'moo ngeh-ree kee',ic:'🤷'},
{l:'Bino',e:'These things',p:'bee-noh',ic:'👐'},
{l:'Ekyo',e:'That thing',p:'eh-choh',ic:'👉'},
{l:'Kale nno',e:'Alright then',p:'kah-leh noh',ic:'👍'},
{l:'Nga bwe kiri',e:'As it is',p:'ngah bweh kee-ree',ic:'💬'},
{l:'Okutegeera',e:'To understand',p:'oh-koo-teh-geh-rah',ic:'💡'},
{l:'Okwetegereza',e:'To be attentive',p:'oh-kweh-teh-geh-reh-zah',ic:'🎯'},
{l:'Mu bufumbo',e:'In marriage',p:'moo boo-foom-boh',ic:'💍'},
{l:'Mu maka',e:'At home',p:'moo mah-kah',ic:'🏠'},
{l:'Ebyafaayo',e:'History / Past events',p:'eh-byah-fah-yoh',ic:'📜'},
{l:'Okwogera',e:'To speak / express',p:'oh-kwoh-geh-rah',ic:'🗣️'},
{l:'Okubuulira',e:'To explain / narrate',p:'oh-koo-boo-lee-rah',ic:'📢'},
{l:'Okukkiriziganya',e:'To agree with each other',p:'oh-koo-kee-ree-zee-gahn-yah',ic:'🤝'},
{l:'Okwewala',e:'To avoid',p:'oh-kweh-wah-lah',ic:'🚫'},
{l:'Okulowoozaako',e:'To think about',p:'oh-koo-loh-woh-zah-koh',ic:'🤔'},
{l:'Obulamu',e:'Life / Existence',p:'oh-boo-lah-moo',ic:'🌱'},
{l:'Ensonga y\'obulamu',e:'Life matter / Issue',p:'en-sohn-gah yoh-boo-lah-moo',ic:'💡'},
{l:'Okunnyonnyola',e:'To explain / clarify',p:'oh-koon-yohn-yoh-lah',ic:'💬'}
]
};

// Additional words appended to reach ~1000 total
// Append these arrays to the existing ones via the app

var VOCAB_EXTRA={
greetings:[
{l:'Tugende wamu',e:'Let us go together',p:'too-gehn-deh wah-moo',ic:'🚶'},
{l:'Nkwetaba',e:'I join you / Greet',p:'n-kweh-tah-bah',ic:'🙋'},
{l:'Okulabirira',e:'To take care',p:'oh-koo-lah-bee-ree-rah',ic:'💚'},
{l:'Ndi bulungi',e:'I am fine',p:'n-dee boo-loon-gee',ic:'😊'},
{l:'Oyagala ki',e:'What do you want?',p:'oh-yah-gah-lah kee',ic:'🤔'},
{l:'Nkwetaba',e:'I am joining you',p:'n-kweh-tah-bah',ic:'🤝'},
{l:'Wano nno',e:'Right here',p:'wah-noh noh',ic:'📍'},
{l:'Beera bulungi',e:'Stay well',p:'beh-rah boo-loon-gee',ic:'💚'},
{l:'Tukimanyi',e:'We know it',p:'too-kee-mahn-yee',ic:'💡'},
{l:'Tugende okulaba',e:'Let us go see',p:'too-gehn-deh oh-koo-lah-bah',ic:'👀'},
{l:'Osiibye otya',e:'How was your day?',p:'oh-see-byeh oh-tyah',ic:'☀️'},
{l:'Weeraba',e:'Farewell (to one)',p:'weh-rah-bah',ic:'👋'},
{l:'Mwerabye',e:'Farewell (to many)',p:'mweh-rah-byeh',ic:'👋'},
{l:'Nsaba oyambeko',e:'Please help me',p:'n-sah-bah oh-yahm-beh-koh',ic:'🤲'},
{l:'Kale bulungi',e:'Alright / Very good',p:'kah-leh boo-loon-gee',ic:'👌'},
{l:'Nkwebaza',e:'I thank you',p:'n-kweh-bah-zah',ic:'🙏'},
{l:'Nkwebazaawo',e:'I appreciate you',p:'n-kweh-bah-zah-woh',ic:'❤️'},
{l:'Nyabo',e:'Yes madam',p:'nyah-boh',ic:'👩'},
{l:'Ddala',e:'Really? / Truly',p:'dah-lah',ic:'😮'},
{l:'Kiki?',e:'What is it?',p:'kee-kee',ic:'🤔'},
{l:'Nkubuulira',e:'I will tell you',p:'n-koo-boo-lee-rah',ic:'📢'},
{l:'Tukolagane',e:'Let us cooperate',p:'too-koh-lah-gah-neh',ic:'🤝'},
{l:'Bwotyo',e:'Like that / In that way',p:'bwoh-tyoh',ic:'👆'},
{l:'Wabula',e:'But then / However',p:'wah-boo-lah',ic:'↩️'},
{l:'Mpa',e:'Give me',p:'m-pah',ic:'🤲'},
{l:'Genda',e:'Go (command)',p:'gehn-dah',ic:'🚶'},
{l:'Jja',e:'Come (command)',p:'jah',ic:'🏃'},
{l:'Tubeere',e:'Let us be',p:'too-beh-reh',ic:'🌿'},
{l:'Teri kizibu',e:'No problem',p:'teh-ree kee-zee-boo',ic:'✅'},
{l:'Kizibu',e:'Problem / Difficulty',p:'kee-zee-boo',ic:'⚠️'}
],
people:[
{l:'Omuwala omukulu',e:'Older girl / Young woman',p:'oh-moo-wah-lah oh-moo-koo-loo',ic:'👩'},
{l:'Omulenzi omukulu',e:'Older boy / Young man',p:'oh-moo-lehn-zee oh-moo-koo-loo',ic:'👨'},
{l:'Omukadde',e:'Old person',p:'oh-moo-kah-deh',ic:'🧓'},
{l:'Omuto',e:'Young person',p:'oh-moo-toh',ic:'🧒'},
{l:'Abakyala',e:'Women (plural)',p:'ah-bah-chah-lah',ic:'👩'},
{l:'Abasajja',e:'Men (plural)',p:'ah-bah-sah-jah',ic:'👨'},
{l:'Ababyeyi',e:'Parents',p:'ah-bah-byeh-yee',ic:'👨‍👩‍👧'},
{l:'Eggwanga',e:'Nation / Tribe',p:'eh-gwahn-gah',ic:'🌍'},
{l:'Omufumbo',e:'Married person',p:'oh-moo-foom-boh',ic:'💍'},
{l:'Abasomesa',e:'Teachers (plural)',p:'ah-bah-soh-meh-sah',ic:'👩‍🏫'},
{l:'Abasawo',e:'Doctors (plural)',p:'ah-bah-sah-woh',ic:'👨‍⚕️'},
{l:'Omwogezi wa gavumenti',e:'Government spokesperson',p:'ohm-woh-geh-zee wah gah-voo-mehn-tee',ic:'🎤'},
{l:'Omukozi',e:'Employee / Worker',p:'oh-moo-koh-zee',ic:'💼'},
{l:'Omwana w\'oluganda',e:'Cousin',p:'ohm-wah-nah woh-loo-gahn-dah',ic:'🧑'},
{l:'Omuganzi',e:'Loved one / Darling',p:'oh-moo-gahn-zee',ic:'❤️'},
{l:'Omwami w\'eggwanga',e:'National chief',p:'ohm-wah-mee weh-gwahn-gah',ic:'👑'},
{l:'Abazukulu',e:'Grandchildren',p:'ah-bah-zoo-koo-loo',ic:'👧👦'},
{l:'Omulamu',e:'In-law',p:'oh-moo-lah-moo',ic:'🤝'},
{l:'Omuko',e:'Son/daughter-in-law',p:'oh-moo-koh',ic:'💒'},
{l:'Omugenzi',e:'Stranger / Visitor',p:'oh-moo-gehn-zee',ic:'🧳'},
{l:'Omuzannyi',e:'Player / Entertainer',p:'oh-moo-zahn-yee',ic:'🎭'},
{l:'Omulambuzi',e:'Translator / Interpreter',p:'oh-moo-lahm-boo-zee',ic:'🗣️'},
{l:'Omukulembeze',e:'Leader',p:'oh-moo-koo-lehm-beh-zeh',ic:'👑'},
{l:'Omukulu w\'essomero',e:'Headteacher',p:'oh-moo-koo-loo weh-soh-meh-roh',ic:'🏫'},
{l:'Ow\'okusooka',e:'First-born',p:'oh-koh-soh-kah',ic:'🥇'},
{l:'Ow\'okuddirira',e:'Last-born',p:'oh-koo-dee-ree-rah',ic:'🥉'},
{l:'Omugole w\'omukazi',e:'Bride',p:'oh-moo-goh-leh woh-moo-kah-zee',ic:'👰'},
{l:'Omugole w\'omusajja',e:'Groom',p:'oh-moo-goh-leh woh-moo-sah-jah',ic:'🤵'},
{l:'Omuyizi',e:'Thief / Criminal',p:'oh-moo-yee-zee',ic:'🚨'},
{l:'Omukyala w\'omwami',e:'Chief\'s wife',p:'oh-moo-chah-lah wohm-wah-mee',ic:'👸'}
],
body:[
{l:'Ensi y\'omubiri',e:'Body surface',p:'en-see yoh-moo-bee-ree',ic:'🧍'},
{l:'Omugezi',e:'Brain',p:'oh-moo-geh-zee',ic:'🧠'},
{l:'Emizimu',e:'Nerves',p:'eh-mee-zee-moo',ic:'⚡'},
{l:'Ensonga z\'omubiri',e:'Body functions',p:'en-sohn-gah zoh-moo-bee-ree',ic:'🫀'},
{l:'Olwazi',e:'Bone',p:'oh-lwah-zee',ic:'🦴'},
{l:'Amaviivi',e:'Nails (fingers/toes)',p:'ah-mah-vee-vee',ic:'💅'},
{l:'Okukeera ennyo',e:'High fever',p:'oh-koo-keh-rah eh-nyoh',ic:'🤒'},
{l:'Ekyoya ky\'okutu',e:'Ear hair / Eardrum area',p:'eh-choh-yah choh-koo-too',ic:'👂'},
{l:'Ekizimba',e:'Growth / Lump',p:'eh-kee-zeem-bah',ic:'🩺'},
{l:'Omusaayi',e:'Bloodstream',p:'oh-moo-sah-yee',ic:'🩸'},
{l:'Ensotoka',e:'Sneeze',p:'en-soh-toh-kah',ic:'🤧'},
{l:'Okukolola',e:'To cough',p:'oh-koo-koh-loh-lah',ic:'😷'},
{l:'Okuvuuma',e:'To breathe',p:'oh-koo-voo-mah',ic:'💨'},
{l:'Okunywa eddagala',e:'To take medicine',p:'oh-koon-ywah eh-dah-gah-lah',ic:'💊'},
{l:'Eddagala',e:'Medicine',p:'eh-dah-gah-lah',ic:'💊'},
{l:'Omulimi',e:'Arm muscle',p:'oh-moo-lee-mee',ic:'💪'},
{l:'Ekifuba',e:'Chest',p:'eh-kee-foo-bah',ic:'🫁'},
{l:'Embiriizi',e:'Kidney',p:'ehm-bee-ree-zee',ic:'🫀'},
{l:'Eyungu',e:'Lung',p:'eh-yoon-goo',ic:'🫁'},
{l:'Olugumba',e:'Joint',p:'oh-loo-goom-bah',ic:'🦴'},
{l:'Omusaayi omulungi',e:'Good health / Healthy blood',p:'oh-moo-sah-yee oh-moo-loon-gee',ic:'🩺'},
{l:'Ensi y\'okutuula',e:'Sitting posture',p:'en-see yoh-koo-too-lah',ic:'🪑'},
{l:'Okubonabona',e:'To suffer / be in pain',p:'oh-koo-boh-nah-boh-nah',ic:'😢'},
{l:'Okutuukirira obulamu',e:'To recover fully',p:'oh-koo-too-kee-ree-rah oh-boo-lah-moo',ic:'💚'},
{l:'Omubiri omulungi',e:'Healthy body',p:'oh-moo-bee-ree oh-moo-loon-gee',ic:'💪'},
{l:'Omusaayi gutereera',e:'Blood pressure',p:'oh-moo-sah-yee goo-teh-reh-rah',ic:'🩺'},
{l:'Omwoyo',e:'Spirit / Soul',p:'ohm-woh-yoh',ic:'✨'},
{l:'Okwekubiriza',e:'To console oneself',p:'oh-kweh-koo-bee-ree-zah',ic:'💛'},
{l:'Obutema',e:'Fatigue / Exhaustion',p:'oh-boo-teh-mah',ic:'😴'},
{l:'Obunafu',e:'Weakness',p:'oh-boo-nah-foo',ic:'😔'}
],
food:[
{l:'Emmere y\'omukaaga',e:'Evening meal',p:'eh-meh-reh yoh-moo-kah-gah',ic:'🌆'},
{l:'Akasimu k\'emmere',e:'Food aroma',p:'ah-kah-see-moo keh-meh-reh',ic:'😋'},
{l:'Okuteeka emmere',e:'To serve food',p:'oh-koo-teh-kah eh-meh-reh',ic:'🍽️'},
{l:'Okunywesa',e:'To make someone drink',p:'oh-koon-yweh-sah',ic:'🥤'},
{l:'Ekyambala ky\'emmere',e:'Food cover / Plate cover',p:'eh-chahm-bah-lah cheh-meh-reh',ic:'🍽️'},
{l:'Omwiiko',e:'Stirring stick / Spoon',p:'ohm-wee-koh',ic:'🥄'},
{l:'Endobo',e:'Pot / Cooking vessel',p:'en-doh-boh',ic:'🍲'},
{l:'Ensuwa',e:'Clay pot',p:'en-soo-wah',ic:'🏺'},
{l:'Akawo',e:'Small bowl',p:'ah-kah-woh',ic:'🥣'},
{l:'Enzigi',e:'Goat meat',p:'en-zee-gee',ic:'🥩'},
{l:'Ebirime',e:'Crops / Harvest',p:'eh-bee-ree-meh',ic:'🌾'},
{l:'Akasoli',e:'Small maize / Popcorn',p:'ah-kah-soh-lee',ic:'🍿'},
{l:'Omuzigo gw\'ente',e:'Cow ghee',p:'oh-moo-zee-goh gwen-teh',ic:'🧈'},
{l:'Obukonde',e:'Cooking banana type',p:'oh-boo-kohn-deh',ic:'🍌'},
{l:'Ensujju',e:'Pumpkin',p:'en-soo-joo',ic:'🎃'},
{l:'Kawunga',e:'Posho flour',p:'kah-woon-gah',ic:'🌾'},
{l:'Omwenge gw\'omuganda',e:'Local brew',p:'ohm-wehn-geh gwoh-moo-gahn-dah',ic:'🍺'},
{l:'Envaamu',e:'Spice / Seasoning',p:'en-vah-moo',ic:'🌶️'},
{l:'Okunonya',e:'To look for food',p:'oh-koo-noh-nyah',ic:'🔍'},
{l:'Okuzimba emmere',e:'To preserve food',p:'oh-koo-zeem-bah eh-meh-reh',ic:'📦'},
{l:'Enva z\'omu nsuku',e:'Garden vegetables',p:'en-vah zoh-moo n-soo-koo',ic:'🥬'},
{l:'Akabisi',e:'Raw food',p:'ah-kah-bee-see',ic:'🥬'},
{l:'Omuddo gw\'ente',e:'Beef sauce',p:'oh-moo-doh gwen-teh',ic:'🥩'},
{l:'Ekyambala',e:'Breakfast',p:'eh-chahm-bah-lah',ic:'🌅'},
{l:'Ensuja',e:'Dinner / Supper',p:'en-soo-jah',ic:'🌙'},
{l:'Obutunda bw\'omucungwa',e:'Orange juice',p:'oh-boo-toon-dah bwoh-moo-coon-gwah',ic:'🍊'},
{l:'Ekijjajja',e:'Grandparent\'s food (yam type)',p:'eh-kee-jah-jah',ic:'🥔'},
{l:'Obuuji',e:'Porridge (thin)',p:'oh-boo-jee',ic:'🥣'},
{l:'Akabazi',e:'Banana type (small)',p:'ah-kah-bah-zee',ic:'🍌'},
{l:'Okusooka okulya',e:'To eat first',p:'oh-koo-soh-kah oh-koo-lyah',ic:'🍽️'}
],
home:[
{l:'Ekisenge ky\'emmere',e:'Dining room',p:'eh-kee-sehn-geh cheh-meh-reh',ic:'🍽️'},
{l:'Ekisenge ky\'okunaaba',e:'Bathroom',p:'eh-kee-sehn-geh choh-koo-nah-bah',ic:'🚿'},
{l:'Oluggi lw\'oluggya',e:'Compound gate',p:'oh-loo-gee lwoh-loo-gyah',ic:'🚪'},
{l:'Ensawo y\'engoye',e:'Clothes bag / Wardrobe',p:'en-sah-woh yeh-ngoh-yeh',ic:'👗'},
{l:'Ekisenge ky\'abaana',e:'Children\'s room',p:'eh-kee-sehn-geh chah-bah-nah',ic:'👧'},
{l:'Omukeeka gw\'okuloga',e:'Sleeping mat',p:'oh-moo-keh-kah gwoh-koo-loh-gah',ic:'🛏️'},
{l:'Omuzigo',e:'Cooking fat / Butter',p:'oh-moo-zee-goh',ic:'🧈'},
{l:'Obwoya',e:'Wool / Fur',p:'oh-bwoh-yah',ic:'🧶'},
{l:'Ekyuma ky\'amaanyi',e:'Electrical appliance',p:'eh-choo-mah chah-mah-nyee',ic:'⚡'},
{l:'Oluggi olukuuma',e:'Security door',p:'oh-loo-gee oh-loo-koo-mah',ic:'🔒'},
{l:'Ensawo y\'emisingi',e:'Rubbish bag',p:'en-sah-woh yeh-mee-seen-gee',ic:'🗑️'},
{l:'Akabina k\'engoye',e:'Wardrobe / Closet',p:'ah-kah-bee-nah kehn-goh-yeh',ic:'🚪'},
{l:'Olutindo lw\'ennyumba',e:'House corridor',p:'oh-loo-teen-doh lweh-nyoom-bah',ic:'🏠'},
{l:'Emmeeza y\'emmere',e:'Dining table',p:'eh-meh-zah yeh-meh-reh',ic:'🪞'},
{l:'Entebe y\'enkulu',e:'Large chair / Sofa',p:'en-teh-beh yeh-n-koo-loo',ic:'🛋️'},
{l:'Omuzigo gw\'ekisenge',e:'Room decoration',p:'oh-moo-zee-goh gweh-kee-sehn-geh',ic:'🎨'},
{l:'Ensawo y\'amabbwa',e:'Money bag / Wallet',p:'en-sah-woh yah-mah-bwah',ic:'👜'},
{l:'Olukomera lw\'oluggya',e:'Compound fence pole',p:'oh-loo-koh-meh-rah lwoh-loo-gyah',ic:'🪵'},
{l:'Ekitabo ky\'amateeka',e:'Rule book',p:'eh-kee-tah-boh chah-mah-teh-kah',ic:'📖'},
{l:'Amaanyi g\'ettaala',e:'Light energy',p:'ah-mah-nyee geh-tah-lah',ic:'💡'},
{l:'Emizigo',e:'Oils / Fats (plural)',p:'eh-mee-zee-goh',ic:'🫙'},
{l:'Ensawo nkulu',e:'Large bag',p:'en-sah-woh n-koo-loo',ic:'🛍️'},
{l:'Omukeeka omulungi',e:'Nice mat',p:'oh-moo-keh-kah oh-moo-loon-gee',ic:'🛏️'},
{l:'Omuliro omulungi',e:'Good fire',p:'oh-moo-lee-roh oh-moo-loon-gee',ic:'🔥'},
{l:'Akabina k\'ensawo',e:'Storage room',p:'ah-kah-bee-nah ken-sah-woh',ic:'📦'},
{l:'Ekyuma ky\'okunaaba',e:'Bathing bucket',p:'eh-choo-mah choh-koo-nah-bah',ic:'🚿'},
{l:'Omukeeka gw\'entebe',e:'Chair cushion',p:'oh-moo-keh-kah gwen-teh-beh',ic:'🪑'},
{l:'Olugoye lw\'oluggi',e:'Door curtain',p:'oh-loo-goh-yeh lwoh-loo-gee',ic:'🚪'},
{l:'Ensawo y\'ekitabo',e:'School bag / Book bag',p:'en-sah-woh yeh-kee-tah-boh',ic:'🎒'},
{l:'Ekyuma ky\'okufumba',e:'Cooking utensil',p:'eh-choo-mah choh-koo-foom-bah',ic:'🍳'}
],
nature:[
{l:'Omuti omukulu',e:'Large tree',p:'oh-moo-tee oh-moo-koo-loo',ic:'🌳'},
{l:'Ekibira ekinene',e:'Big forest',p:'eh-kee-bee-rah eh-kee-neh-neh',ic:'🌲'},
{l:'Amataba g\'omugga',e:'River banks',p:'ah-mah-tah-bah goh-moo-gah',ic:'🏞️'},
{l:'Enkuba enkulu',e:'Heavy rain',p:'en-koo-bah en-koo-loo',ic:'⛈️'},
{l:'Empewo enkulu',e:'Strong wind',p:'ehm-peh-woh en-koo-loo',ic:'💨'},
{l:'Omwezi oguzikira',e:'Full moon',p:'ohm-weh-zee oh-goo-zee-kee-rah',ic:'🌕'},
{l:'Akabonero akatono',e:'Small star',p:'ah-kah-boh-neh-roh ah-kah-toh-noh',ic:'⭐'},
{l:'Olusozi olukutu',e:'Steep hill',p:'oh-loo-soh-zee oh-loo-koo-too',ic:'⛰️'},
{l:'Amazzi amayirikirivu',e:'Flowing water',p:'ah-mah-zee ah-mah-yee-ree-kee-ree-voo',ic:'🏃'},
{l:'Omugga omukulu',e:'Large river',p:'oh-moo-gah oh-moo-koo-loo',ic:'🏞️'},
{l:'Ennyanja enkulu',e:'Large lake',p:'eh-nyahn-jah en-koo-loo',ic:'🌊'},
{l:'Ekibulanku ekitono',e:'Small cloud',p:'eh-kee-boo-lahn-koo eh-kee-toh-noh',ic:'☁️'},
{l:'Omusana omulungi',e:'Good weather',p:'oh-moo-sah-nah oh-moo-loon-gee',ic:'🌤️'},
{l:'Ensiku z\'enkuba',e:'Rainy season',p:'en-see-koo zehn-koo-bah',ic:'🌧️'},
{l:'Enkuutu',e:'Hornbill bird',p:'en-koo-too',ic:'🐦'},
{l:'Enjovu enkadde',e:'Old elephant',p:'en-joh-voo en-kah-deh',ic:'🐘'},
{l:'Empologoma enkazi',e:'Female lion',p:'ehm-poh-loh-goh-mah en-kah-zee',ic:'🦁'},
{l:'Enkima entono',e:'Small monkey',p:'en-kee-mah en-toh-noh',ic:'🐒'},
{l:'Ente n\'omwana',e:'Cow and calf',p:'en-teh nohm-wah-nah',ic:'🐄'},
{l:'Embwa omwana',e:'Puppy',p:'ehm-bwah ohm-wah-nah',ic:'🐕'},
{l:'Emmeme entono',e:'Kitten',p:'eh-meh-meh en-toh-noh',ic:'🐈'},
{l:'Enyonyi enkulu',e:'Large bird / Eagle',p:'eh-nyoh-nyee en-koo-loo',ic:'🦅'},
{l:'Ekibira ky\'obusa',e:'Savanna / Open bush',p:'eh-kee-bee-rah choh-boo-sah',ic:'🌿'},
{l:'Amagulu g\'omuti',e:'Tree roots',p:'ah-mah-goo-loo goh-moo-tee',ic:'🌳'},
{l:'Ebirime by\'ennimiro',e:'Farm crops',p:'eh-bee-ree-meh byeh-nee-mee-roh',ic:'🌾'},
{l:'Omuguwa omukutu',e:'Thick rope / Vine',p:'oh-moo-goo-wah oh-moo-koo-too',ic:'🌿'},
{l:'Akakongovvule',e:'Chameleon',p:'ah-kah-kohn-goh-voo-leh',ic:'🦎'},
{l:'Oluyiira',e:'Anthill',p:'oh-loo-yee-rah',ic:'🐜'},
{l:'Amajju',e:'Dew',p:'ah-mah-joo',ic:'💧'},
{l:'Ekiro ky\'enkuba',e:'Rainy night',p:'eh-kee-roh chehn-koo-bah',ic:'🌧️'}
],
numbers:[
{l:'Makumi mukaaga',e:'Sixty',p:'mah-koo-mee moo-kah-gah',ic:'6️⃣'},
{l:'Makumi musanvu',e:'Seventy',p:'mah-koo-mee moo-sahn-voo',ic:'7️⃣'},
{l:'Makumi munaana',e:'Eighty',p:'mah-koo-mee moo-nah-nah',ic:'8️⃣'},
{l:'Makumi mwenda',e:'Ninety',p:'mah-koo-mee mwehn-dah',ic:'9️⃣'},
{l:'Bikumi bibiri',e:'Two hundred',p:'bee-koo-mee bee-bee-ree',ic:'2️⃣'},
{l:'Enkumi kkumi',e:'Ten thousand',p:'en-koo-mee koo-mee',ic:'🔟'},
{l:'Obukadde bwa maka',e:'Generation',p:'oh-boo-kah-deh bwah mah-kah',ic:'👨‍👩‍👧‍👦'},
{l:'Ssawa emu',e:'One hour',p:'sah-wah eh-moo',ic:'⏰'},
{l:'Ssawa bbiri',e:'Two hours',p:'sah-wah bee-ree',ic:'⏰'},
{l:'Dakkika',e:'Minute',p:'dah-kee-kah',ic:'⏱️'},
{l:'Kasiriivu',e:'Second (time)',p:'kah-see-ree-voo',ic:'⏱️'},
{l:'Ennaku nnya',e:'Four days',p:'eh-nah-koo nyah',ic:'📅'},
{l:'Wiiki bbiri',e:'Two weeks',p:'wee-kee bee-ree',ic:'📆'},
{l:'Emyezi ebiri',e:'Two months',p:'eh-myeh-zee eh-bee-ree',ic:'📅'},
{l:'Emyaka ebiri',e:'Two years',p:'eh-myah-kah eh-bee-ree',ic:'🎆'},
{l:'Mu myaka',e:'In years',p:'moo myah-kah',ic:'📅'},
{l:'Obukadde',e:'Age / Old age',p:'oh-boo-kah-deh',ic:'🧓'},
{l:'Obuto bwe',e:'His/her age (youth)',p:'oh-boo-toh bweh',ic:'👶'},
{l:'Omukaaga ogusatu',e:'Third generation',p:'oh-moo-kah-gah oh-goo-sah-too',ic:'3️⃣'},
{l:'Essaawa z\'ekiro',e:'Night hours',p:'eh-sah-wah zehn-kee-roh',ic:'🌙'},
{l:'Essaawa z\'emisana',e:'Daytime hours',p:'eh-sah-wah zeh-mee-sah-nah',ic:'☀️'},
{l:'Olunaku olw\'okuzaalibwa',e:'Birthday',p:'oh-loo-nah-koo oh-lwoh-koo-zah-lee-bwah',ic:'🎂'},
{l:'Omwaka ogwa nkumi',e:'Millennium',p:'ohm-wah-kah oh-gwah n-koo-mee',ic:'🎆'},
{l:'Ebanga',e:'Period of time / Interval',p:'eh-bahn-gah',ic:'⏳'},
{l:'Obudde',e:'Time / Weather',p:'oh-boo-deh',ic:'⏰'},
{l:'Ebanga lya myaka',e:'Several years period',p:'eh-bahn-gah lyah myah-kah',ic:'📅'},
{l:'Ennaku endala',e:'One more day',p:'eh-nah-koo en-dah-lah',ic:'📅'},
{l:'Enkomerero',e:'End / Conclusion',p:'en-koh-meh-reh-roh',ic:'🏁'},
{l:'Entandikwa',e:'Beginning',p:'en-tahn-dee-kwah',ic:'▶️'},
{l:'Omugaso',e:'Value / Worth',p:'oh-moo-gah-soh',ic:'💎'}
],
adjectives:[
{l:'Omulungi ennyo',e:'Very beautiful',p:'oh-moo-loon-gee eh-nyoh',ic:'😍'},
{l:'Omubi ennyo',e:'Very bad',p:'oh-moo-bee eh-nyoh',ic:'😤'},
{l:'Kimasamasa',e:'Excellent / Outstanding',p:'kee-mah-sah-mah-sah',ic:'🌟'},
{l:'Katerega',e:'Complicated / Tricky',p:'kah-teh-reh-gah',ic:'🤯'},
{l:'Mubbi',e:'Dishonest / Thieving',p:'moo-bee',ic:'🫷'},
{l:'Mutegevu',e:'Intelligent / Perceptive',p:'moo-teh-geh-voo',ic:'🧠'},
{l:'Mwoyo omulungi',e:'Kind-hearted',p:'mwoh-yoh oh-moo-loon-gee',ic:'💚'},
{l:'Mwoyo omubi',e:'Mean / Unkind',p:'mwoh-yoh oh-moo-bee',ic:'😤'},
{l:'Omuteefu',e:'Calm / Peaceful',p:'oh-moo-teh-foo',ic:'🕊️'},
{l:'Ow\'amaanyi',e:'Strong / Energetic',p:'oh-wah-mah-nyee',ic:'💪'},
{l:'Ow\'amagezi',e:'Wise / Knowledgeable',p:'oh-wah-mah-geh-zee',ic:'🧠'},
{l:'Omulekwa',e:'Abandoned / Left out',p:'oh-moo-leh-kwah',ic:'😔'},
{l:'Omwetegevu',e:'Alert / Aware',p:'ohm-weh-teh-geh-voo',ic:'👀'},
{l:'Omugumba',e:'Determined / Persistent',p:'oh-moo-goom-bah',ic:'💪'},
{l:'Omubeezi',e:'Helping / Supportive',p:'oh-moo-beh-zee',ic:'🤝'},
{l:'Omukuusa',e:'The best / The winner',p:'oh-moo-koo-sah',ic:'🥇'},
{l:'Omufubo',e:'Slim / Slender',p:'oh-moo-foo-boh',ic:'🪶'},
{l:'Omukutu',e:'Heavy / Fat',p:'oh-moo-koo-too',ic:'🐘'},
{l:'Omugumu',e:'Firm / Solid',p:'oh-moo-goo-moo',ic:'💎'},
{l:'Omwomu',e:'Soft / Gentle',p:'ohm-woh-moo',ic:'🧸'},
{l:'Ow\'essanyu',e:'Joyful / Happy person',p:'oh-weh-sahn-yoo',ic:'😊'},
{l:'Ow\'olugero',e:'Example / Model person',p:'oh-woh-loo-geh-roh',ic:'🌟'},
{l:'Omusinza',e:'Worshipful / Devout',p:'oh-moo-seen-zah',ic:'🙏'},
{l:'Omukiika',e:'Humble / Modest',p:'oh-moo-kee-kah',ic:'🕊️'},
{l:'Omwenkanye',e:'Equal / Fair',p:'ohm-wehn-kahn-yeh',ic:'⚖️'},
{l:'Kasaana',e:'Bright / Shining',p:'kah-sah-nah',ic:'✨'},
{l:'Kakitiibwa',e:'Respected / Honorable',p:'kah-kee-tee-bwah',ic:'🎖️'},
{l:'Kamasamasa',e:'Top quality',p:'kah-mah-sah-mah-sah',ic:'🥇'},
{l:'Omugazi',e:'Wide / Broad',p:'oh-moo-gah-zee',ic:'↔️'},
{l:'Omupanda',e:'Narrow / Short',p:'oh-moo-pahn-dah',ic:'↕️'},
{l:'Omwetegevu ennyo',e:'Very attentive',p:'ohm-weh-teh-geh-voo eh-nyoh',ic:'🎯'}
],
places:[
{l:'Ekibuga ky\'Uganda',e:'Cities of Uganda',p:'eh-kee-boo-gah choo-gahn-dah',ic:'🏙️'},
{l:'Ennimiro enkulu',e:'Large farm / Plantation',p:'eh-nee-mee-roh en-koo-loo',ic:'🌾'},
{l:'Olusozi lwa Namirembe',e:'Namirembe Hill',p:'oh-loo-soh-zee lwah nah-mee-rehm-beh',ic:'⛪'},
{l:'Ennyanja ya Viktoria',e:'Lake Victoria',p:'eh-nyahn-jah yah veek-toh-ree-yah',ic:'🌊'},
{l:'Ekibira ky\'Bwindi',e:'Bwindi Forest',p:'eh-kee-bee-rah choh-bween-dee',ic:'🌲'},
{l:'Entebe z\'enjovu',e:'Elephant sanctuary',p:'en-teh-beh zen-joh-voo',ic:'🐘'},
{l:'Ekifo ky\'obukebi',e:'Tourist site',p:'eh-kee-foh choh-boo-keh-bee',ic:'🗺️'},
{l:'Omuguudo ogukutu',e:'Main highway',p:'oh-moo-goo-doh oh-goo-koo-too',ic:'🛣️'},
{l:'Eddwaliro lya gavumenti',e:'Government hospital',p:'eh-dwah-lee-roh lyah gah-voo-mehn-tee',ic:'🏥'},
{l:'Ssomero ly\'amaanyi',e:'University / College',p:'soh-meh-roh lyah-mah-nyee',ic:'🎓'},
{l:'Ekifo ky\'okusabira',e:'Place of worship',p:'eh-kee-foh choh-koo-sah-bee-rah',ic:'🙏'},
{l:'Ekivuuniro',e:'Refugee camp',p:'eh-kee-voo-nee-roh',ic:'⛺'},
{l:'Omusulo',e:'Valley / Slope',p:'oh-moo-soo-loh',ic:'⛰️'},
{l:'Ekifo ky\'okuzannya',e:'Playground / Stadium',p:'eh-kee-foh choh-koo-zahn-yah',ic:'🏟️'},
{l:'Ekifo ky\'emmere',e:'Restaurant',p:'eh-kee-foh cheh-meh-reh',ic:'🍽️'},
{l:'Akabuyonjo',e:'Toilet',p:'ah-kah-boo-yohn-joh',ic:'🚽'},
{l:'Ekifo ky\'okwesuulira',e:'Hotel / Lodging',p:'eh-kee-foh choh-kweh-soo-lee-rah',ic:'🏨'},
{l:'Ekifo ky\'amasomero',e:'School compound',p:'eh-kee-foh chah-mah-soh-meh-roh',ic:'🏫'},
{l:'Omukutu ogwa ku ttaka',e:'Dirt road',p:'oh-moo-koo-too oh-gwah koo tah-kah',ic:'🛤️'},
{l:'Ensibirwa',e:'Prison / Jail',p:'en-see-beer-wah',ic:'🔒'},
{l:'Ekifo ky\'amapiini',e:'Port / Dock',p:'eh-kee-foh chah-mah-pee-nee',ic:'⚓'},
{l:'Ekifo ky\'emmeeri',e:'Boat landing',p:'eh-kee-foh cheh-meh-ree',ic:'⛵'},
{l:'Ekifo ky\'enjogera',e:'Cultural centre',p:'eh-kee-foh cheh-njoh-geh-rah',ic:'🎭'},
{l:'Akabiina',e:'Office / Bureau',p:'ah-kah-bee-nah',ic:'🏢'},
{l:'Ekifo ky\'okugula',e:'Shopping area',p:'eh-kee-foh choh-koo-goo-lah',ic:'🛒'},
{l:'Omukutu ogw\'emmotoka',e:'Car road',p:'oh-moo-koo-too oh-gweh-moh-toh-kah',ic:'🚗'},
{l:'Emmotoka',e:'Car / Vehicle',p:'eh-moh-toh-kah',ic:'🚗'},
{l:'Ennyumba y\'obukuumi',e:'Health facility',p:'eh-nyoom-bah yoh-boo-koo-mee',ic:'🏥'},
{l:'Ekifo ky\'emigaso',e:'Industrial zone',p:'eh-kee-foh cheh-mee-gah-soh',ic:'🏭'},
{l:'Akabuyonjo k\'omugwa',e:'Roadside stop',p:'ah-kah-boo-yohn-joh koh-moo-gwah',ic:'🛤️'}
],
society:[
{l:'Abantu ab\'ensi',e:'Citizens',p:'ah-bahn-too ah-ben-see',ic:'👥'},
{l:'Obusobozi',e:'Ability / Capacity',p:'oh-boo-soh-boh-zee',ic:'💪'},
{l:'Ekitibwa',e:'Glory / Fame',p:'eh-kee-tee-bwah',ic:'🌟'},
{l:'Emisango egy\'abantu',e:'Human rights',p:'eh-mee-sahn-goh eh-gyah-bahn-too',ic:'⚖️'},
{l:'Enkulakulana y\'ensi',e:'National development',p:'en-koo-lah-koo-lah-nah yehn-see',ic:'📈'},
{l:'Obwesimbu',e:'Responsibility',p:'oh-bweh-seem-boo',ic:'📋'},
{l:'Okukulakulana',e:'To develop',p:'oh-koo-koo-lah-koo-lah-nah',ic:'🌱'},
{l:'Obukulembeze',e:'Leadership',p:'oh-boo-koo-lehm-beh-zeh',ic:'👑'},
{l:'Eggwanga lya Uganda',e:'The Ugandan nation',p:'eh-gwahn-gah lyah oo-gahn-dah',ic:'🇺🇬'},
{l:'Enkulakulana y\'abantu',e:'People\'s progress',p:'en-koo-lah-koo-lah-nah yah-bahn-too',ic:'📈'},
{l:'Obuwangwa bwa Uganda',e:'Ugandan nationality',p:'oh-boo-wahn-gwah bwah oo-gahn-dah',ic:'🌍'},
{l:'Okukuuma emirembe',e:'To keep the peace',p:'oh-koo-koo-mah eh-mee-rehm-beh',ic:'🕊️'},
{l:'Entalo y\'obuwangwa',e:'National struggle',p:'en-tah-loh yoh-boo-wahn-gwah',ic:'⚔️'},
{l:'Obusuubuzi',e:'Trade / Commerce',p:'oh-boo-soo-boo-zee',ic:'💼'},
{l:'Ensimbi z\'ensi',e:'National treasury',p:'en-seem-bee zen-see',ic:'💰'},
{l:'Amateeka g\'ensi',e:'National laws',p:'ah-mah-teh-kah gehn-see',ic:'⚖️'},
{l:'Olukiiko lw\'ensi',e:'National parliament',p:'oh-loo-kee-koh lwen-see',ic:'🏛️'},
{l:'Omulamuzi',e:'Judge',p:'oh-moo-lah-moo-zee',ic:'⚖️'},
{l:'Omukuumi w\'amateeka',e:'Law enforcer',p:'oh-moo-koo-mee wah-mah-teh-kah',ic:'👮'},
{l:'Enkulaakulana y\'obuntu',e:'Human development',p:'en-koo-lah-koo-lah-nah yoh-boon-too',ic:'🌱'},
{l:'Obusolooza',e:'Democracy',p:'oh-boo-soh-loh-zah',ic:'🗳️'},
{l:'Olutalo lw\'obwenkanya',e:'Fight for equality',p:'oh-loo-tah-loh lwoh-bwehn-kahn-yah',ic:'⚖️'},
{l:'Emirimu gy\'ensi',e:'National work / projects',p:'eh-mee-ree-moo gyehn-see',ic:'🏗️'},
{l:'Obugenzi',e:'Tourism',p:'oh-boo-gehn-zee',ic:'🧳'},
{l:'Amateeka g\'obufumbo',e:'Marriage laws',p:'ah-mah-teh-kah goh-boo-foom-boh',ic:'💍'},
{l:'Enganda',e:'Family / Household unit',p:'en-gahn-dah',ic:'👨‍👩‍👧‍👦'},
{l:'Ekika ky\'Abalangira',e:'Royal clan',p:'eh-kee-kah chah-bah-lahn-gee-rah',ic:'👑'},
{l:'Oluganda lw\'abantu',e:'Human brotherhood',p:'oh-loo-gahn-dah lwah-bahn-too',ic:'🤝'},
{l:'Amaanyi g\'ensi',e:'National power / Strength',p:'ah-mah-nyee gehn-see',ic:'💪'},
{l:'Obufuzi bw\'ensi',e:'National governance',p:'oh-boo-foo-zee bwen-see',ic:'🏛️'}
],
questions:[
{l:'Ekibuuzo ky\'obulamu',e:'Life question',p:'eh-kee-boo-zoh choh-boo-lah-moo',ic:'💡'},
{l:'Okwetegyekera',e:'To prepare oneself',p:'oh-kweh-teh-gyeh-keh-rah',ic:'🎯'},
{l:'Ensonga y\'obukuumi',e:'Health matter',p:'en-sohn-gah yoh-boo-koo-mee',ic:'🏥'},
{l:'Mu kifo ki',e:'In what place?',p:'moo kee-foh kee',ic:'📍'},
{l:'Ku lunaku lwa',e:'On which day?',p:'koo loo-nah-koo lwah',ic:'📅'},
{l:'Mu ssawa mmeka',e:'At what time?',p:'moo sah-wah meh-kah',ic:'⏰'},
{l:'Wa bwe',e:'Exactly where?',p:'wah bweh',ic:'📍'},
{l:'Ani ddala',e:'Who exactly?',p:'ah-nee dah-lah',ic:'❓'},
{l:'Ki ddala',e:'What exactly?',p:'kee dah-lah',ic:'🤔'},
{l:'Gamba',e:'Say / Tell me',p:'gahm-bah',ic:'🗣️'},
{l:'Nnyamba',e:'Help me / Tell me',p:'nyahm-bah',ic:'🤝'},
{l:'Nsonyiwa',e:'Pardon me / Sorry',p:'n-sohn-yee-wah',ic:'😔'},
{l:'Kikoze',e:'What happened?',p:'kee-koh-zeh',ic:'😮'},
{l:'Kigenze',e:'What happened? (past)',p:'kee-gehn-zeh',ic:'❓'},
{l:'Bwatandika',e:'How did it start?',p:'bwah-tahn-dee-kah',ic:'▶️'},
{l:'Lwaki bwatyo',e:'Why like that?',p:'lwah-kee bwah-tyoh',ic:'🤔'},
{l:'Kitegeeka nti',e:'It means that',p:'kee-teh-geh-kah n-tee',ic:'💡'},
{l:'Ntegeera',e:'I understand (confirm)',p:'n-teh-geh-rah',ic:'✅'},
{l:'Simanya bulungi',e:'I don\'t know well',p:'see-mahn-yah boo-loon-gee',ic:'🤷'},
{l:'Nnyamba okutegeera',e:'Help me understand',p:'nyahm-bah oh-koo-teh-geh-rah',ic:'💡'},
{l:'Kibuuzo kino',e:'This question',p:'kee-boo-zoh kee-noh',ic:'❓'},
{l:'Akasiimo kano',e:'This answer',p:'ah-kah-see-moh kah-noh',ic:'💬'},
{l:'Ekibuuzo ekikutu',e:'Hard question',p:'eh-kee-boo-zoh eh-kee-koo-too',ic:'😤'},
{l:'Ekibuuzo ekirungi',e:'Good question',p:'eh-kee-boo-zoh eh-kee-roon-gee',ic:'✅'},
{l:'Okubuuzaako',e:'To ask a bit',p:'oh-koo-boo-zah-koh',ic:'❓'},
{l:'Okwewulira',e:'To feel / sense',p:'oh-kweh-woo-lee-rah',ic:'💭'},
{l:'Okuyiga',e:'To learn',p:'oh-koo-yee-gah',ic:'📚'},
{l:'Okuteebereza ennyo',e:'To think carefully',p:'oh-koo-teh-beh-reh-zah eh-nyoh',ic:'🧠'},
{l:'Okumanya',e:'To know',p:'oh-koo-mahn-yah',ic:'💡'},
{l:'Okuteebereza',e:'To plan / reflect',p:'oh-koo-teh-beh-reh-zah',ic:'📋'}
]
};

// Merge extra vocab into main VOCAB
Object.keys(VOCAB_EXTRA).forEach(function(cat){
  if(VOCAB[cat]) VOCAB[cat]=VOCAB[cat].concat(VOCAB_EXTRA[cat]);
});
